// Simplified Chinese
var translationsZH = {

    TITLE: "裁板大師",
    PRO_VERSION: "專業版",
    PANEL: "部件規格",
    PANELS: "部件數量",
    STOCK_PANEL: "板料尺寸",
    STOCK: "板料尺寸",
    WIDTH: "寬",
    HEIGHT: "長",
    QUANTITY: "數量",
    LABEL: "部件名稱",
    CUT: "裁切位置",
    CUTS: "裁切次數",
    TOTAL_CUTS_NBR: "裁切總數",
    CUT_LENGTH: "裁切長度",
    TOTAL_CUT_LENGTH: "裁切總長",
    DIM: "Dim",
    USED_AREA: "使用面積",
    TOTAL_USED_AREA: "使用總面積",
    WASTED_AREA: "剩餘面積",
    TOTAL_WASTED_AREA: "剩餘總面積",
    WASTED_PANELS: "餘料數量",
    STATS: "統計數據",
    SHEET_STATISTICS: "板料數據",
    NBR_MOSAICS: "用掉板料",
    UNABLE_TO_FIT: "無法放入的部件",
    CUT_THICKNESS: "鋸片厚度/鋸路",

    NAME: "名稱",
    NONE: "無",
    CALCULATE: "開始計算",
    ACCEPT: "確認",
    CANCEL: "取消",
    ERROR: "錯誤",
    OPTIONS: "其他選項",
    SETTINGS: "各項設定",
    LANGUAGE: "語言設定",
    ENABLE: "開啟",
    DISABLE: "關閉",
    ENABLED: "已開啟",
    DISABLED: "已關閉",
    REMOVE: "移除",
    REMOVED: "已移除",
    LOW: "Low",
    NORMAL: "Normal",
    HIGH: "High",
    UPGRADE: "升級",
    ABOUT: "關於此應用程式",
    DELETE: "刪除",
    SAVED: "儲存",
    DELETED: "已刪除",
    LOADED: "已匯入",
    LOGOUT: "登出",
    ADD_NEW: "新增檔案",

    ADD_LINE: "新增一列",
    LOAD: "匯入清單",
    SAVE_LIST: "儲存清單",
    ENABLE_DISABLE_ALL: "開啟/關閉所有設定",
    DELETE_ALL: "清空",
    EXPORT_CSV: "匯出成CSV",
    IMPORT_CSV: "從CSV匯入",
    CLEAR_LIST: "是否清除資料?",
    RESET_DATA: "新的空白專案",

    EMAIL: "Email",
    PASSWORD: "密碼",
    CONFIRM_PASSWORD: "確認密碼",
    SIGN_IN: "登入",
    SIGN_OUT: "登出",
    SIGN_UP: "註冊",
    OR: "or",
    SIGN_IN_GOOGLE: "以Google帳戶登入",
    FORGOT_PASS: "忘記密碼?",
    PASS_RESET: "重設密碼",
    PASS_RESET_MSG: "請輸入 Email，你將收到重設密碼的連結。",
    PASS_SAVE_MSG: "請輸入新的密碼。",
    LOGIN_REQUEST: "請先登入帳號",

    PDF_PAGE: "頁",
    REPORT_AN_ISSUE: "問題回報",
    OPTIMIZATION_PRIORITY: "最佳化排序",
    LEAST_WASTED_AREA: "最少餘料",
    LEAST_NUMBER_OF_CUTS: "最少裁切數",

    ZOOM_IN: "放大",
    ZOOM_OUT: "縮小",
    INCREASE_FONT_SIZE: "放大字體",
    DECREASE_FONT_SIZE: "縮小字體",
    RESET_ZOOM: "重設檢視畫面",
    ROTATE_90: "旋轉90º",
    PANEL_LABELS: "標示部件名稱",
    COLORED_PANELS: "以顏色區分不同部件",
    SHOW_CUTS: "裁切順序",
    SHOW_DIMENSIONS: "尺標",

    SAVE_PROJECT: "儲存專案",
    LOAD_PROJECT: "載入專案",
    NO_SAVED_DATA: "沒有儲存資訊可顯示",
    OVERWRITE: "覆蓋檔案",
    SAVE_AS: "另存為",
    ALREADY_EXISTS: "檔案已存在",

    INITIALIZING: "初始化中",
    COMPUTING: "電腦運算中",
    SEARCHING_BEST: "正在搜尋最佳方案",
    EXPORT_PDF: "匯出成PDF檔",
    EXPORT_IMG: "匯出成影像檔",
    EXPORTING_PDF: "正在生成PDF",
    EXPORTING_IMG: "正在生成影像",
    NOTHING_TO_EXPORT: "沒有可匯出資料",
    CLICK_TO_ACCEPT: "點擊螢幕以接受成果",
    TAP_TO_ACCEPT: "點擊螢幕以接受成果",
    MSG_NO_PANELS: "沒有選定部件",
    MSG_NO_STOCK_PANELS: "沒有選定板料",
    // TODO: OPTIMIZATION_LEVEL: "優化程度",
    IMAGE_PAN_ZOOM: "鎖定平移與縮放頁面",
    FORCE_ONE_STOCK_PANEL: "從板料數量擇一使用",

    UNITS: "單位",
    DECIMAL_PLACES: "小數位數",
    GENERIC: "公英制通用 (16.5)",
    MM: "公釐 (16.5 mm)",
    CM: "公分 (16.5 cm)",
    INCHES: "英吋 (16.5\")",
    FEET_INCHES: "十進位制英尺英寸 (1' 4.5\")",
    FEET_INCHES_FRAC: "分數制英尺與英寸 (1' 4 1/2\")",
    INCHES_FRAC: "分數制英寸 (16 1/2\")",

    MATERIAL: "板料種類",
    CREATE_MATERIAL: "建立新板料種類",
    MSG_NO_STOCK_MATERIAL: "指定板料種類無效",
    CONSIDER_MATERIALS: "依板料種類規劃",

    EDGE_BANDING: "封邊條",
    EDGE_BAND: "邊條",
    TOP_EDGE_BAND: "上邊條",
    LEFT_EDGE_BAND: "左邊條",
    BOTTOM_EDGE_BAND: "下邊條",
    RIGHT_EDGE_BAND: "右邊條",
    CREATE_EDGE_BAND: "建立新邊條樣式",

    ORIENTATION_MATTERS: "依木紋方向規劃",
    NO_GRAIN: "不須考慮木紋方向",
    HORIZONTAL_GRAIN: "木紋依照寬邊走",
    VERTICAL_GRAIN: "木紋依照長邊走",

    CALCULATIONS_PER_WEEK: "每週可計算次數",
    UNLIMITED: "不限次數",
    FREE: "免費",
    MONTHLY: "計月",
    TERMS_OF_SERVICE: "使用條款",
    PRIVACY_POLICY: "隱私權政策",
    CONTACT_EMAIL: "聯繫 Email:",

    SERVER_UNAVAILABLE: "抱歉，伺服器正忙線中，請稍後再試.",
    TASK_ALREADY_RUNNING: "一次只能跑一個算式",
    TOO_MANY_PANELS: "無法計算超過1000片的部件",
    TOO_MANY_STOCK_PANELS: "無法計算超過1000片的板料",
    LIMITS_REACHED: "您每日的免費次數已達上限， 敬請考慮升等成為付費會員，支持應用程式的發展。",
    OPEN_RUNNING_CALC: "Open running calculation",

    ABOUT_MSG_1: "「裁板大師」是專門針對優化裁切板料的應用程式。這項應用程式，可依照每人手邊現有的板材規格、以及裁切最佳化的需求，勾選適當的選項來計算、產生裁切圖。",
    ABOUT_MSG_2: "裡面所有功能，都有一個每週可免費的使用次數。",
    ABOUT_MSG_3: "如果您覺得這個應用程式很好用，請考慮升級至專業版本，來支持應用程式的發展。或者，您也可以透過網站升級會員帳號，那麼就能夠同時使用安卓專業版，及網頁版進階功能。 ",
    SUBSCRIPTION_MSG_1: "升級至以下付費版本，以支持「裁板大師」",
    SUBSCRIPTION_ADDITINAL_MSG_1: "現在訂購，馬上就可以使用。",
    SUBSCRIPTION_ADDITINAL_MSG_2: "每個結算週期首日，會主動從您的 PayPal 帳戶扣款。",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "啟用服務的當日，就是每個月結週期的首日。",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "不足一月，按一月計",
    SUBSCRIPTION_ADDITINAL_MSG_5: "您可以隨時從您的PayPal帳戶取消訂購，並且可以繼續使用這項服務，直到結算週期結束為止。",

    SUBSCRIPTION_INVOICE: "付費單據可透過以下申請 ",

    TRY_WEB_MSG: "「裁板大師」也有網頁版。 網頁版的進階功能，有專業伺服器在運算，運算速度會更快。 ",

    SAVED_ITEM_LIMIT_REACHED: "已經達到可儲存上限",
    SUBSCRIPTION_ACTIVE: "您的訂購已開通",
    SUBSCRIPTION_PLAN: "訂購方案",
    CONTRIBUTE: "支持",
    SUBSCRIBE: "訂購",
    ACTIVE: "開通",
    PER_DAY: "每日",
    CLIENT_STATS: "資訊",
    ALLOWED_CALCULATIONS: "計算上限",
    CALCULATION_SPEED: "計算速度",
    SAVED_ITEMS: "已儲存專案",
    PRICE: "費用",
    GOLD: "黃金會員",
    SILVER: "銀階會員",

    DIMENSIONS_TO_LABELS: "以板料長寬替換部件名稱",
    REPLACE_LABELS_QUESTION: "是否替換掉現有部件名稱?",

    WHATS_NEW: "最新資訊",

    FILENAME: "檔案名稱",
    FONT_SIZE: "字體大小",
    BIG: "大",
    HUGE: "最大",
    SEARCH: "搜尋",
    RENAME: "重新命名",
    RENAMED: "已重新命名",
    SAVE: "存檔",

    PDF_HEADER_TEXT: "Header text",
    PDF_ADDITIONAL_TEXT: "Additional text",
    PDF_SHOW_SUMMARY: "顯示概要",
    PDF_SHOW_DATE: "顯示日期",
    PDF_SHOW_CUTS_TABLE: "顯示裁切圖",

    UNSAVED_CHANGES: "所做的變更尚未儲存，是否繼續?",
    ALREADY_EXISTS: "檔名已存在!",

    GENERIC_ERROR_MSG: "發生錯誤!",

    PRO_FEATURE: "付費版功能",
    PRO_FEATURES: "專業版功能",

    CUT_ORIENTATION_PREFERENCE: "裁切最佳化選項",
    CUT_ORIENTATION_PREFERENCE_NONE: "最佳化",
    CUT_ORIENTATION_PREFERENCE_WIDTH: "沿版寬裁切",
    CUT_ORIENTATION_PREFERENCE_LENGTH: "沿版長裁切",

    SUPPORT_PRIORITY: "優先技術支援",
    MEDIUM: "Medium",

    FORCE_SERVER_SIDE_CALC: "用專業伺服器計算",
    ANDROID_PRO_VERSION: "安卓專業版應用程式",

    NO_ADS: "無廣告",
    SUBSCRIPTION_REQUEST: "付費會員才能使用這項功能",
    UPGRADE_PLAN: "升級",

    SUBSCRIPTION_APLICABLE: "付費版功能，同時適用於網路與安卓版，解開您帳戶所有功能。",
    SUBSCRIPTION_FEATURES_DEVICE: "不論在何處、使用何種裝置，只要登入您的帳號，就能使用所有付費版功能，以及存取所有的檔案",

    CANCEL_SUBSCRIPTION: "確定要取消您的付費會員?",
    SUBSCRIPTION_CANCELED: "已取消",
    SUBSCRIPTION_CANCEL_ERROR: "抱歉，出了一些問題，請稍後再試。 您可以從您的 PayPal 帳戶中，取消訂購，或是寫信到 support@cutlistoptimizer.com 提出申請",
    MANAGE_SUBSCRIPTION: "管理訂購",

    MINIMUM_TRIM_DIMENSION: "最小裁切尺寸",
    GROUP_EQUAL_MOSAICS: "將裁切方式相同的板料堆疊起來",
    AUTO: "自動",
    NEVER: "永不",
    ALWAYS: "總是",

    SURPLUS: "surplus",
    RESULT: "Result"
};