// Turkish
var translationsTR = {
    TITLE: "CutList Optimizer",
    PRO_VERSION: "Pro veriyon",
    PANEL: "Parça",
    PANELS: "Parçalar",
    STOCK_PANEL: "Malzeme levhaları",
    STOCK: "Malzeme Levhaları",
    WIDTH: "Genişlik",
    HEIGHT: "Uzunluk",
    QUANTITY: "Adet",
    LABEL: "Etiket",
    CUT: "Kesim",
    CUTS: "Kesimler",
    TOTAL_CUTS_NBR: "Toplam kesim",
    CUT_LENGTH: "Kesim uzunluğu",
    TOTAL_CUT_LENGTH: "Toplam kesim uzunluğu",
    DIM: "Boyut",
    USED_AREA: "Kullanılan alan",
    TOTAL_USED_AREA: "Toplam kullanılan alan",
    WASTED_AREA: "Boş alan",
    TOTAL_WASTED_AREA: "Toplam boş alan",
    WASTED_PANELS: "Boş parça",
    STATS: "Genel istatistikler",
    SHEET_STATISTICS: "Levha istatistikleri",
    NBR_MOSAICS: "Kullanılan malzeme levhası",
    UNABLE_TO_FIT: "Levhaya sığmıyor",
    CUT_THICKNESS: "Kesme / Bıçak Ağzı / Çentik Kalılığı",

    NAME: "ad",
    NONE: "Yok",
    CALCULATE: "Hesapla",
    ACCEPT: "Onayla",
    CANCEL: "İptal",
    ERROR: "Hata",
    OPTIONS: "Seçenekler",
    SETTINGS: "Ayarlar",
    LANGUAGE: "Dil",
    ENABLE: "Aktif",
    DISABLE: "Pasif",
    ENABLED: "Aktif",
    DISABLED: "Pasif",
    REMOVE: "Sil",
    REMOVED: "Silindi",
    LOW: "Düşük",
    NORMAL: "Normal",
    HIGH: "Yüksek",
    UPGRADE: "Yükselt",
    ABOUT: "hakkında",
    DELETE: "Sil",
    SAVED: "Kayıtlı",
    DELETED: "silindi",
    LOADED: "Yüklendi",
    LOGOUT: "Çıkış Yap",
    ADD_NEW: "Yeni ekle",

    ADD_LINE: "Yeni satır ekle",
    LOAD: "Liste yükle",
    SAVE_LIST: "Listeyi kaydet",
    ENABLE_DISABLE_ALL: "Tümünü Etkinleştir / Devre Dışı Bırak",
    DELETE_ALL: "Temizle",
    EXPORT_CSV: "CSV'ye aktar",
    IMPORT_CSV: "CSV yükle",
    CLEAR_LIST: "Listeyi temizle?",
    RESET_DATA: "Tüm veriyi temizle",

    EMAIL: "E-posta",
    PASSWORD: "Parola",
    CONFIRM_PASSWORD: "Şifreyi Onayla",
    SIGN_IN: "Oturum aç",
    SIGN_OUT: "Oturumu Kapat",
    SIGN_UP: "Kaydol",
    OR: "veya",
    SIGN_IN_GOOGLE: "Google ile giriş yap",
    FORGOT_PASS: "Parolanızı mı unuttunuz?",
    PASS_RESET: "Parola sıfırlama",
    PASS_RESET_MSG: "Lütfen E-postanızı girin. Yeni bir şifre oluşturmak için bir link alacaksınız.",
    PASS_SAVE_MSG: "Lütfen yeni şifrenizi girin.",
    LOGIN_REQUEST: "Lütfen önce oturum açın",

    PDF_PAGE: "sayfa",
    REPORT_AN_ISSUE: "Sorun bildirin",
    OPTIMIZATION_PRIORITY: "Optimizasyon önceliği",
    LEAST_WASTED_AREA: "En az boş alan",
    LEAST_NUMBER_OF_CUTS: "En az kesim sayısı",

    ZOOM_IN: "Yakınlaştır",
    ZOOM_OUT: "Uzaklaştır",
    INCREASE_FONT_SIZE: "Yazı Tipi Boyutunu Büyüt",
    DECREASE_FONT_SIZE: "Yazı Tipi Boyutunu Küçült",
    RESET_ZOOM: "Görünümü SIFIRLAMAK",
    ROTATE_90: "90º döndür",
    PANEL_LABELS: "Parça etiketleri",
    COLORED_PANELS: "Parçaları renklendir",
    SHOW_CUTS: "Kesim çizgileri",
    SHOW_DIMENSIONS: "boyutlar",

    SAVE_PROJECT: "Projeyi kaydet",
    LOAD_PROJECT: "Proje yükle",
    NO_SAVED_DATA: "Kaydedilmiş veri yok!",
    OVERWRITE: "Üzerine Yaz",
    SAVE_AS: "Farklı kaydet",
    ALREADY_EXISTS: "Zaten var",

    INITIALIZING: "Başlatılıyor...",
    COMPUTING: "Hesaplanıyor",
    SEARCHING_BEST: "En iyi çözüm aranıyor",
    EXPORT_PDF: "PDF'ye Aktar",
    EXPORT_IMG: "Resim'e aktar",
    EXPORTING_PDF: "PDF Oluşturuluyor",
    EXPORTING_IMG: "Resim Oluşturuluyor",
    NOTHING_TO_EXPORT: "Dışa aktarılacak bir şey yok",
    CLICK_TO_ACCEPT: "Çözümü kabul etmek için tıklayın",
    TAP_TO_ACCEPT: "Çözümü kabul etmek için dokunun",
    MSG_NO_PANELS: "Parça belirtilmedi.",
    MSG_NO_STOCK_PANELS: "Belirtilen malzeme levhası yok.",
    // TODO: OPTIMIZATION_LEVEL: "Optimizasyon seviyesi",
    IMAGE_PAN_ZOOM: "Görüntü kaydırma ve yakınlaştırmayı etkinleştir",
    FORCE_ONE_STOCK_PANEL: "Malzemeden sadece bir tane levha kullan",

    UNITS: "Birimler",
    DECIMAL_PLACES: "Ondalık",
    GENERIC: "Genel (16.5)",
    MM: "Milimetre (16.5 mm)",
    CM: "Santimetre (16.5 cm)",
    INCHES: "Inc (16.5\")",
    FEET_INCHES: "Ondalık ölçüler & Inc (1' 4.5\")",
    FEET_INCHES_FRAC: "Ondalık ölçüler & Inc (1' 4 1/2\")",
    INCHES_FRAC: "Kesirli İnç (16 1/2 \")",

    MATERIAL: "Malzeme",
    CREATE_MATERIAL: "Yeni malzeme türü oluştur",
    MSG_NO_STOCK_MATERIAL: "Gerekli malzemenin stok sayfası yok",
    CONSIDER_MATERIALS: "Malzemeyi düşünün",

    EDGE_BANDING: "Kenar bantlama",
    EDGE_BAND: "Kenar bantı",
    TOP_EDGE_BAND: "Üst kenar bantı",
    LEFT_EDGE_BAND: "Sol kenar bantı",
    BOTTOM_EDGE_BAND: "Alt kenar bantı",
    RIGHT_EDGE_BAND: "Sağ kenar bantı",
    CREATE_EDGE_BAND: "Yeni kenar bandı türü oluşturma",

    ORIENTATION_MATTERS: "Kesim yönünü seç",
    NO_GRAIN: "Kesim yönü değerlendirmesi yok",
    HORIZONTAL_GRAIN: "Yatay Kesim",
    VERTICAL_GRAIN: "Dikey kesim",

    CALCULATIONS_PER_WEEK: "Haftalık hesaplamalar",
    UNLIMITED: "sınırsız",
    FREE: "Bedava",
    MONTHLY: "aylık",
    TERMS_OF_SERVICE: "Kullanım Şartları",
    PRIVACY_POLICY: "Gizlilik Politikası",
    CONTACT_EMAIL: "İletişim E-posta:",

    SERVER_UNAVAILABLE: "Sunucu şu anda bazı sorunlar yaşıyor, lütfen daha sonra tekrar deneyin.",
    TASK_ALREADY_RUNNING: "Aynı anda yalnızca bir hesaplama çalıştırılabilir",
    TOO_MANY_PANELS: "1000'den fazla panel ile hesaplama yapılamıyor",
    TOO_MANY_STOCK_PANELS: "1000'den fazla stok sayfasıyla hesaplama yapılamıyor",
    LIMITS_REACHED: "Ücretsiz günlük hesaplama sınırınıza ulaşıldı. Lütfen gelişimi desteklemeyi düşünün.",
    OPEN_RUNNING_CALC: "Açık hesaplama",

    ABOUT_MSG_1: "CutList Optimizer, panel kesme optimizasyonu için hedeflenen bir uygulamadır.",
    ABOUT_MSG_2: "Gerekli parçaları ekleyerek mevcut malzeme levhalarına göre optimize edilmiş kesim düzenleri oluşturun.",
    ABOUT_MSG_3: "Bu uygulamayı yararlı bulursanız, gelişimini desteklemek için lütfen Pro sürümüne geçmeyi düşünün. Alternatif olarak, hesabınızı web sitesinden yükseltebilirsiniz ve hem Android Pro sürümüne hem de web sitesi premium özelliklerine erişebilirsiniz.",
    SUBSCRIPTION_MSG_1: "Pro sürümüne yükselterek CutList Optimizer'a katkıda bulunun.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "Abonelik hemen yürürlüğe girecek",
    SUBSCRIPTION_ADDITINAL_MSG_2: "PayPal hesabınızdan her faturalandırma döngüsünün başında otomatik olarak ödeme alınacaktır",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "İlk aylık faturalandırma döngüsü, hizmeti etkinleştirdiğiniz gün başlar",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "Kısmi aylar için geri ödeme veya kredi yoktur",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Aboneliğinizi PayPal hesabınızdan istediğiniz zaman iptal edebilir ve faturalandırma döneminiz sona erene kadar hizmeti kullanmaya devam edebilirsiniz.",

    TRY_WEB_MSG: "CutList Optimizer web üzerinde de mevcuttur. Web sürümü optimize edilmiş özellikler sunar ve daha hızlı hesaplamalar sağlayan özel bir sunucudan yararlanır: "
};