// Japanese
var translationsJA = {

    TITLE: "カットリスト　オプティマイザ",
    PRO_VERSION: "プロ　バージョン",
    PANEL: "パネル",
    PANELS: "パネル",
    STOCK_PANEL: "原反",
    STOCK: "原反",
    WIDTH: "幅",
    HEIGHT: "長さ",
    QUANTITY: "数量",
    LABEL: "ラベル",
    CUT: "カット",
    CUTS: "カット数",
    TOTAL_CUTS_NBR: "合計カット数",
    CUT_LENGTH: "Cut length",
    TOTAL_CUT_LENGTH: "計長さカット",
    DIM: "寸法",
    USED_AREA: "使用面積",
    TOTAL_USED_AREA: "合計使用面積",
    WASTED_AREA: "端材面積",
    TOTAL_WASTED_AREA: "合計端材面積",
    WASTED_PANELS: "端材パネル",
    STATS: "プロジェクト全体統計",
    SHEET_STATISTICS: "原反統計",
    NBR_MOSAICS: "使用原反枚数",
    UNABLE_TO_FIT: "加工不可パネル",
    CUT_THICKNESS: "刃 / 刃の厚み",

    NAME: "名前",
    NONE: "無し",
    CALCULATE: "実行",
    ACCEPT: "採用",
    CANCEL: "キャンセル",
    ERROR: "エラー",
    OPTIONS: "オプション",
    SETTINGS: "設定",
    LANGUAGE: "言語",
    ENABLE: "有効",
    DISABLE: "無効",
    ENABLED: "使用可能",
    DISABLED: "使用不可",
    REMOVE: "削除",
    REMOVED: "削除済み",
    LOW: "低",
    NORMAL: "中",
    HIGH: "高",
    UPGRADE: "アップグレード",
    ABOUT: "について",
    DELETE: "削除",
    SAVED: "保存済み",
    DELETED: "削除済み",
    LOADED: "ロード済み",
    LOGOUT: "ログアウト",
    ADD_NEW: "新規追加",

    ADD_LINE: "行挿入",
    LOAD: "リストロードする",
    SAVE_LIST: "リストを保存",
    ENABLE_DISABLE_ALL: "全て有効 / 無効",
    DELETE_ALL: "クリア",
    EXPORT_CSV: "CSVエクスポート",
    IMPORT_CSV: "CSVインポート",
    CLEAR_LIST: "リストクリア？",
    RESET_DATA: "新規プロジェクト",

    EMAIL: "Email",
    PASSWORD: "パスワード",
    CONFIRM_PASSWORD: "確認用パスワード",
    SIGN_IN: "ログイン",
    SIGN_OUT: "ログアウト",
    SIGN_UP: "新規登録",
    OR: "OR",
    SIGN_IN_GOOGLE: "Sign in with Google",
    FORGOT_PASS: "パスワードを忘れた？",
    PASS_RESET: "パスワードリセット",
    PASS_RESET_MSG: "Emailを入力してください、新しいパスワード設定用のリンクを送ります。",
    PASS_SAVE_MSG: "新しいパスワード入力",
    LOGIN_REQUEST: "先ずログインしてください。",

    PDF_PAGE: "ページ",
    REPORT_AN_ISSUE: "問題を報告",
    OPTIMIZATION_PRIORITY: "最適化の優先順位",
    LEAST_WASTED_AREA: "無駄の少ない面積順",
    LEAST_NUMBER_OF_CUTS: "カット数少ない順",

    ZOOM_IN: "ズームイン",
    ZOOM_OUT: "ズームアウト",
    INCREASE_FONT_SIZE: "テキストを拡大する",
    DECREASE_FONT_SIZE: "テキストを縮小する",
    RESET_ZOOM: "ビューリセット",
    ROTATE_90: "90º 回転",
    PANEL_LABELS: "パネルラベル表示",
    COLORED_PANELS: "色塗りつぶしパネル",
    SHOW_CUTS: "カット順",
    SHOW_DIMENSIONS: "寸法",

    SAVE_PROJECT: "プロジェクトを保存",
    LOAD_PROJECT: "プロジェクトをロード",
    NO_SAVED_DATA: "保存済みのデータ存在しません。",
    OVERWRITE: "上書き",
    SAVE_AS: "として保存",
    ALREADY_EXISTS: "既に存在しています。",

    INITIALIZING: "実行中",
    COMPUTING: "計算中",
    SEARCHING_BEST: "最適な提案を検索しています。",
    EXPORT_PDF: "PDFとしてエクスポート",
    EXPORT_IMG: "画像としてエクスポート",
    EXPORTING_PDF: "PDF発行中",
    EXPORTING_IMG: "画像発行中",
    NOTHING_TO_EXPORT: "エクスポートするものがないです。",
    CLICK_TO_ACCEPT: "提案を採用するためにクリックしてください。",
    TAP_TO_ACCEPT: "提案を採用するためにタップしてください。",
    MSG_NO_PANELS: "パネルは選定されていません。",
    MSG_NO_STOCK_PANELS: "原反は選定されていません。",
    // TODO: OPTIMIZATION_LEVEL: "最適レベル",
    IMAGE_PAN_ZOOM: "ズーム/パンをロックする",
    FORCE_ONE_STOCK_PANEL: "在庫から１枚原反のみ使用する",

    UNITS: "単位",
    DECIMAL_PLACES: "小数位",
    GENERIC: "汎用 (16.5)",
    MM: "ミリメートル (16.5 mm)",
    CM: "センチメートル (16.5 cm)",
    INCHES: "インチ (16.5\")",
    FEET_INCHES: "少数フィート＆インチ(1' 4.5\")",
    FEET_INCHES_FRAC: "分数フィート＆インチ(1' 4 1/2\")",
    INCHES_FRAC: "分数インチ (16 1/2\")",

    MATERIAL: "材料",
    CREATE_MATERIAL: "新規材料の作成",
    MSG_NO_STOCK_MATERIAL: "必要な材料は在庫にございません。",
    CONSIDER_MATERIALS: "材料を考慮する",

    EDGE_BANDING: "エッジバンディング",
    EDGE_BAND: "エッジバンド",
    TOP_EDGE_BAND: "トップエッジバンド",
    LEFT_EDGE_BAND: "左エッジバンド",
    BOTTOM_EDGE_BAND: "下エッジバンド",
    RIGHT_EDGE_BAND: "右エッジバンド",
    CREATE_EDGE_BAND: "新規エッジバンド作成",

    ORIENTATION_MATTERS: "柄方向を考慮する",
    NO_GRAIN: "柄方向を考慮しない",
    HORIZONTAL_GRAIN: "柄方向は横",
    VERTICAL_GRAIN: "柄方向は縦",

    CALCULATIONS_PER_WEEK: "１週間当りの計算数",
    UNLIMITED: "無制限",
    FREE: "無料",
    MONTHLY: "毎月",
    TERMS_OF_SERVICE: "利用規約",
    PRIVACY_POLICY: "個人情報保護方針",
    CONTACT_EMAIL: "連絡用Email:",

    SERVER_UNAVAILABLE: "サーバー側で問題が発生しています、時間経ってから再度やり直してください。",
    TASK_ALREADY_RUNNING: "一度に実行できる計算は１回だけです。",
    TOO_MANY_PANELS: "1000枚を超えるパネルで計算を実行できません。",
    TOO_MANY_STOCK_PANELS: "1000枚以上の在庫原反で計算できません。",
    LIMITS_REACHED: "1日の無料計算限度額に達しました。 開発支援をご検討ください。",
    OPEN_RUNNING_CALC: "計算中プロジェクトを開く",

    ABOUT_MSG_1: "カットリストオプトマイザーは、パネルカットの最適化を対象としたアプリケーションです。 最適なパネルカットを制作するために、利用可能な在庫原反に最適化された切断パターンを生成します。",
    ABOUT_MSG_2: "すべての機能は、1週間あたりの限られた数の計算内で無料で完全に利用できます。",
    ABOUT_MSG_3: "このアプリが便利だと思ったら、その開発をサポートするためにProバージョンへのアップグレードを検討してください。 または、ウェブサイト内でアカウントをアップグレードすると、AndroidProバージョンとウェブサイトのプレミアム機能の両方にアクセスできるようになります。",
    SUBSCRIPTION_MSG_1: "サブスクリプションプランにアップグレードして、カットリストオプトマイザーに貢献します。",
    SUBSCRIPTION_ADDITINAL_MSG_1: "サブスクリプションはすぐに有効になります。",
    SUBSCRIPTION_ADDITINAL_MSG_2: "PayPalアカウントは、各請求サイクルの開始時に自動的に請求されます。",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "最初の毎月の請求サイクルは、サービスをアクティブ化した日から始まります。",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "月残り（日割計算）のの払い戻しやクレジットはありません",
    SUBSCRIPTION_ADDITINAL_MSG_5: "PayPalアカウントでいつでもサブスクリプションをキャンセルでき、請求期間が終了するまでサービスを引き続き使用できます。",

    SUBSCRIPTION_INVOICE: "VAT請求書の要請は ",

    TRY_WEB_MSG: "カットリストオプトマイザーはWebでも入手できます。 Webバージョンは最適化された機能を提供し、より高速な計算を提供する専用サーバーを利用します。",

    SAVED_ITEM_LIMIT_REACHED: "保存されたアイテムの最大許容数に達しました。",
    SUBSCRIPTION_ACTIVE: "サブスクリプションがアクティブになりました",
    SUBSCRIPTION_PLAN: "サブスクリプションプラン",
    CONTRIBUTE: "寄付する",
    SUBSCRIBE: "申し込む",
    ACTIVE: "アクティブ",
    PER_DAY: "日当り",
    CLIENT_STATS: "統計",
    ALLOWED_CALCULATIONS: "可能計算数",
    CALCULATION_SPEED: "計算実行スピード",
    SAVED_ITEMS: "保存済みアイテム",
    PRICE: "価格",
    GOLD: "ゴールド",
    SILVER: "シルバー",

    DIMENSIONS_TO_LABELS: "ラベルに寸法を記入します。",
    REPLACE_LABELS_QUESTION: "現在のラベルを置き換えますか？",

    WHATS_NEW: "新着情報",

    FILENAME: "ファイル名",
    FONT_SIZE: "フォントサイズ",
    BIG: "大",
    HUGE: "特大",
    SEARCH: "検索",
    RENAME: "名前を変更",
    RENAMED: "名前変更済み",
    SAVE: "保存",

    PDF_HEADER_TEXT: "ヘッダーテキスト",
    PDF_ADDITIONAL_TEXT: "追加テキスト",
    PDF_SHOW_SUMMARY: "概要を表示",
    PDF_SHOW_DATE: "日付を表示",
    PDF_SHOW_CUTS_TABLE: "カットテーブルを表示",

    UNSAVED_CHANGES: "保存されていない変更はすべて失われます。 続けますか？",
    ALREADY_EXISTS: "既に存在しています。",

    GENERIC_ERROR_MSG: "エラーが発生しました。",

    PRO_FEATURE: "プレミアム機能",
    PRO_FEATURES: "プレミアム機能",

    CUT_ORIENTATION_PREFERENCE: "カット較正",
    CUT_ORIENTATION_PREFERENCE_NONE: "最適",
    CUT_ORIENTATION_PREFERENCE_WIDTH: "幅に沿ったカットを好む",
    CUT_ORIENTATION_PREFERENCE_LENGTH: "長手に沿ったカットを好む",

    SUPPORT_PRIORITY: "優先サポート",
    MEDIUM: "中",

    FORCE_SERVER_SIDE_CALC: "専用サーバーで計算を実行する",
    ANDROID_PRO_VERSION: "AndroidProアプリ",

    NO_ADS: "広告なし",
    SUBSCRIPTION_REQUEST: "この機能には、アクティブなサブスクリプションプランのアカウントが必要です",
    UPGRADE_PLAN: "アップグレード",

    SUBSCRIPTION_APLICABLE: "サブスクリプションはウェブサイトとAndroidアプリの両方に適用され、アカウントのすべての機能のロックを解除されます。",
    SUBSCRIPTION_FEATURES_DEVICE: "アカウントにログインするだけで、サブスクリプション機能と保存されたデータをどのデバイスでも利用できるようになります。",

    CANCEL_SUBSCRIPTION: "アクティブなサブスクリプションをキャンセルしてもよろしいですか？",
    SUBSCRIPTION_CANCELED: "サブスクリプションがキャンセルされました。",
    SUBSCRIPTION_CANCEL_ERROR: "何かが間違っています。後でもう一度試してください。または、PayPalアカウントでサブスクリプションをキャンセルするか、電子メールでsupport@cutlistoptimizer.comに問い合わせることもできます。",
    MANAGE_SUBSCRIPTION: "サブスクリプションを管理する",

    MINIMUM_TRIM_DIMENSION: "最小カット寸法",
    GROUP_EQUAL_MOSAICS: "同じ寸法のパネルをまとめる。",
    AUTO: "自動",
    NEVER: "無効",
    ALWAYS: "いつも"
};
