// Spanish
var translationsES = {

    TITLE: "CutList Optimizer",
    PRO_VERSION: "Versión Pro",
    PANEL: "Panel",
    PANELS: "Paneles",
    STOCK_PANEL: "Hoja del archivo",
    STOCK: "Hojas en inventario",
    WIDTH: "Anchura",
    HEIGHT: "Longitud",
    QUANTITY: "Cant.",
    LABEL: "Etiqueta",
    CUT: "Corte",
    CUTS: "Cortes",
    TOTAL_CUTS_NBR: "Cortes totales",
    CUT_LENGTH: "Longitud de corte",
    TOTAL_CUT_LENGTH: "Longitud total de corte",
    DIM: "Medida",
    USED_AREA: "Área utilizada",
    TOTAL_USED_AREA: "Área total utilizada",
    WASTED_AREA: "Área desperdiciada",
    TOTAL_WASTED_AREA: "Área total desperdiciada",
    WASTED_PANELS: "Paneles desperdiciados",
    STATS: "Estadísticas globales",
    SHEET_STATISTICS: "Estadísticas de la hoja",
    NBR_MOSAICS: "Hojas del archivo utilizadas",
    UNABLE_TO_FIT: "Imposible de encajar",
    CUT_THICKNESS: "Grosor del corte",

    NAME: "Nombre",
    NONE: "Ningun",
    CALCULATE: "Calcular",
    ACCEPT: "Aceptar",
    CANCEL: "Cancelar",
    ERROR: "Error",
    OPTIONS: "Opciones",
    SETTINGS: "Ajustes",
    LANGUAGE: "Idioma",
    ENABLE: "Habilitar",
    DISABLE: "Deshabilitar",
    ENABLED: "Habilitado",
    DISABLED: "Desabilitado",
    REMOVE: "Eliminar",
    REMOVED: "Retirado",
    LOW: "Bajo",
    NORMAL: "Normal",
    HIGH: "Alto",
    UPGRADE: "Ascender",
    ABOUT: "Acerca de",
    DELETE: "Eliminar",
    SAVED: "Salvado",
    DELETED: "Eliminado",
    LOADED: "Cargado",
    LOGOUT: "Cerrar sesión",
    ADD_NEW: "Agregar nuevo",

    ADD_LINE: "Añadir nueva línea",
    LOAD: "Cargar lista",
    SAVE_LIST: "Guardar lista",
    ENABLE_DISABLE_ALL: "Habilitar / deshabilitar todo",
    DELETE_ALL: "Claro",

    EXPORT_CSV: "Export to CSV",
    IMPORT_CSV: "Importar desde CSV",
    CLEAR_LIST: "¿Limpiar lista?",
    RESET_DATA: "Nuevo proyecto en blanco",

    EMAIL: "Email",
    PASSWORD: "Contraseña",
    CONFIRM_PASSWORD: "Confirmar contraseña",
    SIGN_IN: "Registrarse",
    SIGN_OUT: "Desconectar",
    SIGN_UP: "Regístrate",
    OR: "o",
    SIGN_IN_GOOGLE: "Inicia sesión con Google",
    FORGOT_PASS: "¿Olvidaste tu contraseña?",
    PASS_RESET: "Restablecimiento de contraseña",
    PASS_RESET_MSG: "Por favor introduzca su correo electrónico. Recibirá un enlace para crear una nueva contraseña.",
    PASS_SAVE_MSG: "Por favor ingrese su nueva contraseña.",
    LOGIN_REQUEST: "Inicia sesión primero",

    PDF_PAGE: "página",
    REPORT_AN_ISSUE: "Reportar un problema",
    OPTIMIZATION_PRIORITY: "Prioridad de optimización",
    LEAST_WASTED_AREA: "Menor área desperdiciada",
    LEAST_NUMBER_OF_CUTS: "Menor número de cortes",

    ZOOM_IN: "Acercar",
    ZOOM_OUT: "Alejar",
    INCREASE_FONT_SIZE: "Aumenta el tamaño de la fuente",
    DECREASE_FONT_SIZE: "Disminuir tamaño de fuente",
    RESET_ZOOM: "Reestablecer vista",
    ROTATE_90: "Girar 90º",
    PANEL_LABELS: "Etiquetas en los paneles",
    COLORED_PANELS: "Paneles rellenos de color",
    SHOW_CUTS: "Orden de los cortes",

    SAVE_PROJECT: "Guardar proyecto",
    LOAD_PROJECT: "Cargar proyecto",
    NO_SAVED_DATA: "No hay datos guardados.",
    OVERWRITE: "Sobrescribir",
    SAVE_AS: "Guardar como",
    ALREADY_EXISTS: "Ya existe",

    INITIALIZING: "Inicializando",
    COMPUTING: "Calculando...",
    SEARCHING_BEST: "Buscando la mejor solución",
    EXPORT_PDF: "Exportar a PDF",
    EXPORT_IMG: "Exportar a imagen",
    EXPORTING_PDF: "Exportando a PDF...",
    EXPORTING_IMG: "Exportando a imagen...",
    NOTHING_TO_EXPORT: "Nada que exportar",
    CLICK_TO_ACCEPT: "Hacer clic para aceptar la solución",
    TAP_TO_ACCEPT: "Tocar para aceptar la solución",
    MSG_NO_PANELS: "No se ha especificado ningún panel.",
    MSG_NO_STOCK_PANELS: "No se ha especificado ninguna hoja del archivo.",
    // TODO: OPTIMIZATION_LEVEL: "Nivel de optimización",
    IMAGE_PAN_ZOOM: "Habilitar panorámica de imagen y zoom",
    FORCE_ONE_STOCK_PANEL: "Usar sólo una hoja del archivo",
    UNITS: "Unidades",
    DECIMAL_PLACES: "Lugares decimales",
    GENERIC: "Genérico (16.5)",
    MM: "Milímetros (16.5 mm)",
    CM: "Centímetros (16,5 cm)",
    INCHES: "Pulgadas (16.5 \")",
    FEET_INCHES: "Pies y pulgadas decimales (1 '4.5 \")",
    FEET_INCHES_FRAC: "Pies y pulgadas fraccionales (1 '4 1/2 \")",
    INCHES_FRAC: "Pulgadas fraccionales (16 1/2 \")",

    MATERIAL: "Material",
    CREATE_MATERIAL: "Crear nuevo tipo de material",
    MSG_NO_STOCK_MATERIAL: "No hay una hoja de material disponible disponible",
    CONSIDER_MATERIALS: "Considerar material",

    EDGE_BANDING: "Franja de borde",
    EDGE_BAND: "Banda de la orilla",
    TOP_EDGE_BAND: "Banda de borde superior",
    LEFT_EDGE_BAND: "Banda de borde izquierdo",
    BOTTOM_EDGE_BAND: "Banda de borde inferior",
    RIGHT_EDGE_BAND: "Banda del borde derecho",
    CREATE_EDGE_BAND: "Crear nuevo tipo de banda de borde",

    ORIENTATION_MATTERS: "Considere la dirección del grano",
    NO_GRAIN: "Sin consideración de grano",
    HORIZONTAL_GRAIN: "Grano a lo largo del ancho",
    VERTICAL_GRAIN: "Grano a lo largo",

    CALCULATIONS_PER_WEEK: "Cálculos semanales",
    UNLIMITED: "ilimitado",
    FREE: "Gratis",
    MONTHLY: "mensual",
    TERMS_OF_SERVICE: "Términos de servicio",
    PRIVACY_POLICY: "Política de privacidad",
    CONTACT_EMAIL: "Email de contacto:",

    SERVER_UNAVAILABLE: "El servidor está experimentando algunos problemas, intente nuevamente más tarde.",
    TASK_ALREADY_RUNNING: "Solo se permite ejecutar un cálculo a la vez",
    TOO_MANY_PANELS: "No se puede realizar el cálculo con más de 1000 paneles",
    TOO_MANY_STOCK_PANELS: "No se puede realizar el cálculo con más de 1000 hojas de inventario",
    LIMITS_REACHED: "Se ha alcanzado su límite de cálculo diario gratuito. Por favor considere apoyar el desarrollo.",
    OPEN_RUNNING_CALC: "Cálculo de carrera abierta",

    ABOUT_MSG_1: "CutList Optimizer es una aplicación destinada a la optimización de corte de paneles. Genera patrones de corte optimizados basados ​​en las hojas de stock disponibles al anidar las piezas requeridas.",
    ABOUT_MSG_2: "Todas las funciones están totalmente disponibles de forma gratuita en un número limitado de cálculos por semana.",
    ABOUT_MSG_3: "Si encuentra útil esta aplicación, considere actualizar a la versión Pro para apoyar su desarrollo. Alternativamente, puede actualizar su cuenta dentro del sitio web y tendrá acceso tanto a la versión Android Pro como a las características premium del sitio web.",
    SUBSCRIPTION_MSG_1: "Contribuya a CutList Optimizer actualizando a la versión Pro.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "La suscripción entrará en vigencia de inmediato.",
    SUBSCRIPTION_ADDITINAL_MSG_2: "Su cuenta de PayPal se cargará automáticamente al comienzo de cada ciclo de facturación.",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "El primer ciclo de facturación mensual comienza el día en que activa el servicio.",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "No hay reembolsos ni créditos por meses parciales.",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Puede cancelar su suscripción en cualquier momento en su cuenta PayPal y puede continuar utilizando el servicio hasta que finalice su período de facturación",

    TRY_WEB_MSG: "CutList Optimizer también está disponible en la web. La versión web proporciona funciones optimizadas y hace uso de un servidor dedicado que proporciona cálculos más rápidos: "
};
