// Netherlands
var translationsNL = {

    TITLE: "CutList Optimizer",
    PRO_VERSION: "Pro versie",
    PANEL: "Paneel",
    PANELS: "Panelen",
    STOCK_PANEL: "Voorraad plaat",
    STOCK: "Voorraad platen",
    WIDTH: "Breedte",
    HEIGHT: "Lengte",
    QUANTITY: "Aantal",
    LABEL: "Label",
    CUT: "Zaagsnede",
    CUTS: "Zaagsnedes",
    TOTAL_CUTS_NBR: "Totaal zaagsnedes",
    CUT_LENGTH: "Zaag lengte",
    TOTAL_CUT_LENGTH: "Totaal zaag lengte",
    DIM: "Afm",
    USED_AREA: "Gebruikt gebied",
    TOTAL_USED_AREA: "Totaal gebruikt gebied",
    WASTED_AREA: "Verspild gebied",
    TOTAL_WASTED_AREA: "Totaal verspild gebied",
    WASTED_PANELS: "Verspilde panelen",
    STATS: "Globale statistieken",
    SHEET_STATISTICS: "Plaat statistieken",
    NBR_MOSAICS: "Gebruikte voorraad platen",
    UNABLE_TO_FIT: "Past niet",
    CUT_THICKNESS: "Zaagsnede / Zaagblad dikte",

    NAME: "Naam",
    NONE: "Geen",
    CALCULATE: "Berekenen",
    ACCEPT: "Accepteer",
    CANCEL: "Annuleren",
    ERROR: "Error",
    OPTIONS: "Opties",
    SETTINGS: "Instellingen",
    LANGUAGE: "Taal",
    ENABLE: "Inschakelen",
    DISABLE: "Uitschakelen",
    ENABLED: "Ingeschakeld",
    DISABLED: "Uitgeschakeld",
    REMOVE: "Verwijderen",
    REMOVED: "Verwijderd",
    LOW: "Laat",
    NORMAL: "Normaal",
    HIGH: "Hoog",
    UPGRADE: "Upgrade",
    ABOUT: "Over",
    DELETE: "Verwijder",
    SAVED: "Opgeslagen",
    DELETED: "Verwijderd",
    LOADED: "Geladen",
    LOGOUT: "Uitloggen",
    ADD_NEW: "Nieuw toevoegen",

    ADD_LINE: "Nieuwe regel toevoegen",
    LOAD: "Laad lijst",
    SAVE_LIST: "Bewaar lijst",
    ENABLE_DISABLE_ALL: "Alles inschakelen / uitschakelen",
    DELETE_ALL: "Opnieuw",
    EXPORT_CSV: "Exporteren naar CSV",
    IMPORT_CSV: "Importeren van CSV",
    CLEAR_LIST: "Lijst vernieuwen?",
    RESET_DATA: "Nieuw leeg project",

    EMAIL: "E-mail",
    PASSWORD: "Wachtwoord",
    CONFIRM_PASSWORD: "Bevestig wachtwoord",
    SIGN_IN: "Aanmelden",
    SIGN_OUT: "Afmelden",
    SIGN_UP: "Inschrijven",
    OR: "of",
    SIGN_IN_GOOGLE: "Log in met Google",
    FORGOT_PASS: "Je wachtwoord vergeten?",
    PASS_RESET: "Wachtwoord resetten",
    PASS_RESET_MSG: "Vul alstublieft uw e-mailadres in. U ontvangt een link om een ​​nieuw wachtwoord aan te maken.",
    PASS_SAVE_MSG: "Voer uw nieuwe wachtwoord in.",
    LOGIN_REQUEST: "Log eerst in",

    PDF_PAGE: "pagina",
    REPORT_AN_ISSUE: "Een probleem melden",
    OPTIMIZATION_PRIORITY: "Optimalisatie prioriteit",
    LEAST_WASTED_AREA: "Minst verspilde ruimte",
    LEAST_NUMBER_OF_CUTS: "Minimaal aantal zaagsnedes",

    ZOOM_IN: "In zoomen",
    ZOOM_OUT: "Uit zoomen",
    INCREASE_FONT_SIZE: "Vergroot de lettergrootte",
    DECREASE_FONT_SIZE: "Verklein de lettergrootte",
    RESET_ZOOM: "Weergave resetten",
    ROTATE_90: "Draai 90º",
    PANEL_LABELS: "Etiketten op panelen",
    COLORED_PANELS: "Kleur gevulde panelen",
    SHOW_CUTS: "Zaagsnede orde",
    SHOW_DIMENSIONS: "Dimensies",

    SAVE_PROJECT: "Bewaar dit project",
    LOAD_PROJECT: "Laad project",
    NO_SAVED_DATA: "Geen opgeslagen gegevens",
    OVERWRITE: "Overschrijven",
    SAVE_AS: "Opslaan als",
    ALREADY_EXISTS: "Bestaat al",

    INITIALIZING: "Initialiseren",
    COMPUTING: "Computergebruik",
    SEARCHING_BEST: "Op zoek naar de beste indeling",
    EXPORT_PDF: "Exporteren naar PDF",
    EXPORT_IMG: "Exporteren naar afbeelding",
    EXPORTING_PDF: "PDF genereren",
    EXPORTING_IMG: "Afbeelding genereren",
    NOTHING_TO_EXPORT: "Niets om te exporteren",
    CLICK_TO_ACCEPT: "Klik om de indeling te accepteren",
    TAP_TO_ACCEPT: "Tik om de indeling te accepteren",
    MSG_NO_PANELS: "Geen panelen gespecificeerd",
    MSG_NO_STOCK_PANELS: "Geen voorraad platen opgegeven",
    // TODO: OPTIMIZATION_LEVEL: "Optimalisatieniveau",
    IMAGE_PAN_ZOOM: "Vergrendel Kantelen & Inzoomen",
    FORCE_ONE_STOCK_PANEL: "Gebruik slechts één plaat uit voorraad",

    UNITS: "Eenheden",
    DECIMAL_PLACES: "Decimalen",
    GENERIC: "Algemeen (16.5)",
    MM: "Millimeters (16.5 mm)",
    CM: "Centimeters (16.5 cm)",
    INCHES: "Inches (16.5\")",
    FEET_INCHES: "Decimale Feet & Inches (1' 4.5\")",
    FEET_INCHES_FRAC: "Fractioneel Feet & Inches (1' 4 1/2\")",
    INCHES_FRAC: "Fractioneel Inches (16 1/2\")",

    MATERIAL: "Materiaal",
    CREATE_MATERIAL: "Maak een nieuw materiaalsoort",
    MSG_NO_STOCK_MATERIAL: "Geen voorraad plaat van het benodigde materiaal beschikbaar",
    CONSIDER_MATERIALS: "Overweeg materiaal",

    EDGE_BANDING: "Randafwerking",
    EDGE_BAND: "Kantenband",
    TOP_EDGE_BAND: "Bovenkant kantenband",
    LEFT_EDGE_BAND: "Links kantenband",
    BOTTOM_EDGE_BAND: "Onderkant kantenband",
    RIGHT_EDGE_BAND: "Rechts kantenband",
    CREATE_EDGE_BAND: "Maak een nieuw type kantenband",

    ORIENTATION_MATTERS: "Overweeg de richting van de korrel",
    NO_GRAIN: "Geen graanoverweging",
    HORIZONTAL_GRAIN: "Nerf langs de breedte",
    VERTICAL_GRAIN: "Nerf langs de lengte",

    CALCULATIONS_PER_WEEK: "Berekeningen per week",
    UNLIMITED: "oneindig",
    FREE: "Gratis",
    MONTHLY: "maandelijks",
    TERMS_OF_SERVICE: "Servicevoorwaarden",
    PRIVACY_POLICY: "Privacybeleid",
    CONTACT_EMAIL: "Contact E-mail:",

    SERVER_UNAVAILABLE: "De server ondervindt momenteel enkele problemen, probeer het later opnieuw.",
    TASK_ALREADY_RUNNING: "Er mag slechts één berekening tegelijk worden uitgevoerd",
    TOO_MANY_PANELS: "Kan geen berekening uitvoeren met meer dan 1000 panelen",
    TOO_MANY_STOCK_PANELS: "Kan geen berekening uitvoeren met meer dan 1000 voorraad platen",
    LIMITS_REACHED: "Uw gratis dagelijkse berekeningslimiet is bereikt.  Overweeg om de ontwikkeling te ondersteunen.",
    OPEN_RUNNING_CALC: "Open lopende berekening",

    ABOUT_MSG_1: "CutList Optimizer is een applicatie bedoeld voor optimalisatie van het zagen van panelen.  Het genereert geoptimaliseerde zaagpatronen op basis van de beschikbare voorraadplaten door de vereiste onderdelen te nesten.",
    ABOUT_MSG_2: "Alle functies zijn volledig gratis beschikbaar binnen een beperkt aantal berekeningen per week.",
    ABOUT_MSG_3: "Als u deze app nuttig vindt, overweeg dan om te upgraden naar de Pro-versie om de ontwikkeling ervan te ondersteunen.  Als alternatief kunt u uw account op de website upgraden en krijgt u toegang tot zowel de Android Pro-versie als de premiumfuncties van de website.",
    SUBSCRIPTION_MSG_1: "Draag bij aan CutList Optimizer door te upgraden naar een abonnement.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "Het abonnement wordt onmiddellijk van kracht",
    SUBSCRIPTION_ADDITINAL_MSG_2: "Uw PayPal-rekening wordt aan het begin van elke betalingscyclus automatisch in rekening gebracht",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "De eerste maandelijkse betalingscyclus begint op de dag dat u de service activeert",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "Er zijn geen terugbetalingen of tegoeden voor gedeeltelijke maanden",
    SUBSCRIPTION_ADDITINAL_MSG_5: "U kunt uw abonnement op elk moment in uw PayPal-rekening annuleren en u kunt de service blijven gebruiken totdat uw factureringsperiode afloopt",

    SUBSCRIPTION_INVOICE: "Btw-factuur kan worden aangevraagd ",

    TRY_WEB_MSG: "CutList Optimizer is ook beschikbaar op internet. De webversie biedt geoptimaliseerde functies en maakt gebruik van een speciale server voor snellere berekeningen:: ",

    SAVED_ITEM_LIMIT_REACHED: "Maximaal toegestaan aantal opgeslagen items bereikt",
    SUBSCRIPTION_ACTIVE: "Je abonnement is nu actief",
    SUBSCRIPTION_PLAN: "Abonnements plan",
    CONTRIBUTE: "Bijdragen",
    SUBSCRIBE: "Abboneren",
    ACTIVE: "Actief",
    PER_DAY: "per dag",
    CLIENT_STATS: "Statistieken",
    ALLOWED_CALCULATIONS: "Toegestane berekeningen",
    CALCULATION_SPEED: "Berekenings snelheid",
    SAVED_ITEMS: "Saved items",
    PRICE: "Prijs",
    GOLD: "Goud",
    SILVER: "Zilver",

    DIMENSIONS_TO_LABELS: "Vul labels in met afmetingen",
    REPLACE_LABELS_QUESTION: "Huidige labels vervangen?",

    WHATS_NEW: "Wat is er nieuw",

    FILENAME: "Bestandsnaam",
    FONT_SIZE: "Lettertype grootte",
    BIG: "Groot",
    HUGE: "Zeer groot",
    SEARCH: "Zoeken",
    RENAME: "Hernoemen",
    RENAMED: "Hernoemd",
    SAVE: "Opslaan",

    PDF_HEADER_TEXT: "Kop tekst",
    PDF_ADDITIONAL_TEXT: "Extra tekst",
    PDF_SHOW_SUMMARY: "Samenvatting weergeven",
    PDF_SHOW_DATE: "Toon datum",
    PDF_SHOW_CUTS_TABLE: "Toon zaagsnedes tabel",

    UNSAVED_CHANGES: "Alle niet-opgeslagen wijzigingen gaan verloren. Wil je doorgaan?",
    ALREADY_EXISTS: "bestaat al!",

    GENERIC_ERROR_MSG: "Er is een fout opgetreden!",

    PRO_FEATURE: "Premium Functie",
    PRO_FEATURES: "Premium Functie's",

    CUT_ORIENTATION_PREFERENCE: "Zaag Oriëntatie",
    CUT_ORIENTATION_PREFERENCE_NONE: "Optimaal",
    CUT_ORIENTATION_PREFERENCE_WIDTH: "Geef de voorkeur aan zagen in de breedte",
    CUT_ORIENTATION_PREFERENCE_LENGTH: "Geef de voorkeur aan zagen in de lengte",

    SUPPORT_PRIORITY: "Prioriteit ondersteuning",
    MEDIUM: "Gemiddeld",

    FORCE_SERVER_SIDE_CALC: "Voer berekeningen uit op een speciale server",
    ANDROID_PRO_VERSION: "Android Pro app",

    NO_ADS: "Geen advertenties",
    SUBSCRIPTION_REQUEST: "Deze functie vereist een account met een actief abonnement",
    UPGRADE_PLAN: "Upgrade",

    SUBSCRIPTION_APLICABLE: "Het abonnement is van toepassing op zowel de website als de Android-app, waardoor alle functies voor uw account worden ontgrendeld",
    SUBSCRIPTION_FEATURES_DEVICE: "Abonnementsfuncties en opgeslagen gegevens zijn voor u beschikbaar op elk apparaat door eenvoudig in te loggen op uw account",

    CANCEL_SUBSCRIPTION: "Weet u zeker dat u uw actieve abonnement wilt annuleren?",
    SUBSCRIPTION_CANCELED: "Abonnement opgezegd",
    SUBSCRIPTION_CANCEL_ERROR: "Er is iets misgegaan, probeer het later opnieuw. U kunt ook uw abonnement op uw PayPal-account annuleren of een e-mail sturen naar support@cutlistoptimizer.com",
    MANAGE_SUBSCRIPTION: "Beheer abonnement",

    MINIMUM_TRIM_DIMENSION: "Minimale trimmaat",
    GROUP_EQUAL_MOSAICS: "Voorraad panelen met dezelfde zaag lay-out",
    AUTO: "Auto",
    NEVER: "Nooit",
    ALWAYS: "Altijd",

    SURPLUS: "overschot",
    RESULT: "Resultaat",


    ADDRESS: "Adres",
    CITY: "Stad",
    ZIP_CODE: "Postcode",
    COUNTRY: "Land",
    VAT: "BTW-nummer"
};