// Korean
var translationsKR = {

    TITLE: "PECO",
    PRO_VERSION: "베타버전",
    PANEL: "주문 판재",
    PANELS: "주문 판재",
    STOCK_PANEL: "재고 판재",
    STOCK: "재고 판재",
    WIDTH: "폭",
    HEIGHT: "길이",
    QUANTITY: "수량",
    LABEL: "비고",
    CUT: "재단",
    CUTS: "재단",
    TOTAL_CUTS_NBR: "총 재단 횟수",
    CUT_LENGTH: "재단 길이",
    TOTAL_CUT_LENGTH: "총 재단 길이",
    DIM: "Dim",
    USED_AREA: "사용 면적",
    TOTAL_USED_AREA: "총 사용 면적",
    WASTED_AREA: "자투리 면적",
    TOTAL_WASTED_AREA: "총 자투리 면적",
    WASTED_PANELS: "총 자투리 갯수",
    STATS: "전체 통계",
    SHEET_STATISTICS: "사용 판재 통계",
    NBR_MOSAICS: "사용 재고 판재",
    UNABLE_TO_FIT: "치수가 맞지 않음",
    CUT_THICKNESS: "톱날 두께",

    NAME: "이름",
    NONE: "없음",
    CALCULATE: "계산",
    ACCEPT: "승인",
    CANCEL: "취소",
    ERROR: "오류",
    OPTIONS: "부가기능",
    SETTINGS: "설정",
    LANGUAGE: "언어",
    ENABLE: "가능",
    DISABLE: "불가능",
    ENABLED: "가능",
    DISABLED: "불가능",
    REMOVE: "삭제",
    REMOVED: "삭제",
    LOW: "낮음",
    NORMAL: "보통",
    HIGH: "높음",
    UPGRADE: "업그레이드",
    ABOUT: "기타",
    DELETE: "삭제",
    SAVED: "저장",
    DELETED: "삭제",
    LOADED: "로드",
    LOGOUT: "로그아웃",
    ADD_NEW: "추가",

    ADD_LINE: "행 추가",
    LOAD: "리스트 불러오기",
    SAVE_LIST: "리스트 저장하기",
    ENABLE_DISABLE_ALL: "전체 선택/해제",
    DELETE_ALL: "전체 삭제",
    EXPORT_CSV: "내보내기(CSV)",
    IMPORT_CSV: "불러오기(CSV)",
    CLEAR_LIST: "리스트를 초기화하겠습니까?",
    RESET_DATA: "새 페이지",

    EMAIL: "이메일",
    PASSWORD: "비밀번호",
    CONFIRM_PASSWORD: "비밀번호 확인",
    SIGN_IN: "로그인",
    SIGN_OUT: "로그아웃",
    SIGN_UP: "회원가입",
    OR: "또는",
    SIGN_IN_GOOGLE: "구글로 로그인",
    FORGOT_PASS: "비밀번호를 잊어버리셨나요?",
    PASS_RESET: "비밀번호 초기화",
    PASS_RESET_MSG: "이메일을 입려해주세요. 새로운 비밀번호 변경 시 이메일로 전송됩니다.",
    PASS_SAVE_MSG: "비밀번호를 입력해주세요.",
    LOGIN_REQUEST: "로그인을 진행해주세요.",

    PDF_PAGE: "페이지",
    REPORT_AN_ISSUE: "문제 보고",
    OPTIMIZATION_PRIORITY: "최적화 우선순위",
    LEAST_WASTED_AREA: "자투리 면적 최소화",
    LEAST_NUMBER_OF_CUTS: "재단 횟수 최소화",

    ZOOM_IN: "확대",
    ZOOM_OUT: "축소",
    INCREASE_FONT_SIZE: "글자 확대",
    DECREASE_FONT_SIZE: "글자 축소",
    RESET_ZOOM: "화면 리셋",
    ROTATE_90: "90º 회전",
    PANEL_LABELS: "판재 비고",
    COLORED_PANELS: "색상이 채워진 판재",
    SHOW_CUTS: "재단 주문",
    SHOW_DIMENSIONS: "치수",

    SAVE_PROJECT: "프로젝트 저장",
    LOAD_PROJECT: "프로젝트 불러오기",
    NO_SAVED_DATA: "저장된 데이터 없음",
    OVERWRITE: "덮어쓰기",
    SAVE_AS: "다른 이름으로 저장",
    ALREADY_EXISTS: "이미 존재함",

    INITIALIZING: "정렬 중",
    COMPUTING: "계산 중",
    SEARCHING_BEST: "최적 배치 찾는 중",
    EXPORT_PDF: "내보내기(PDF)",
    EXPORT_IMG: "내보내기(JPEG)",
    EXPORTING_PDF: "PDF 생성 중",
    EXPORTING_IMG: "이미지 생성 중",
    NOTHING_TO_EXPORT: "내보내기 없음",

    // TODO: Review other languages
    CLICK_TO_ACCEPT: "클릭하면 작업이 중지됩니다.",
    TAP_TO_ACCEPT: "탭하면 작업이 중지됩니다.",

    MSG_NO_PANELS: "지정된 저장 판재 없음",
    MSG_NO_STOCK_PANELS: "지정된 재고 판재 없음",
    // TODO: OPTIMIZATION_LEVEL: "Optimization level",
    IMAGE_PAN_ZOOM: "기능 잠금",
    FORCE_ONE_STOCK_PANEL: "재고 판재에서 한 장만 사용",

    UNITS: "단위 표기",
    DECIMAL_PLACES: "소수점 이하 자리 수",
    GENERIC: "표기 없음 (16.5)",
    MM: "밀리미터 (16.5 mm)",
    CM: "센티미터 (16.5 cm)",
    INCHES: "인치 (16.5\")",
    FEET_INCHES: "십진수 피트 & 인치 (1' 4.5\")",
    FEET_INCHES_FRAC: "분수형 피트 & 인치 (1' 4 1/2\")",
    INCHES_FRAC: "분수형 인치 (16 1/2\")",

    MATERIAL: "소재",
    CREATE_MATERIAL: "새 소재 유형 만들기",
    MSG_NO_STOCK_MATERIAL: "사용 가능한 재고 판재 없음",
    CONSIDER_MATERIALS: "소재 고려",

    EDGE_BANDING: "엣지 밴딩",
    EDGE_BAND: "엣지 밴드",
    TOP_EDGE_BAND: "상단 엣지 밴드",
    LEFT_EDGE_BAND: "좌측 엣지 밴드",
    BOTTOM_EDGE_BAND: "하단 엣지 밴드",
    RIGHT_EDGE_BAND: "우측 엣지 밴드",
    CREATE_EDGE_BAND: "엣지 밴드 타입 생성",

    ORIENTATION_MATTERS: "나뭇결 고려",
    NO_GRAIN: "나뭇결 고려 없음",
    HORIZONTAL_GRAIN: "폭 방향 나뭇결",
    VERTICAL_GRAIN: "길이 방향 나뭇결",

    CALCULATIONS_PER_WEEK: "주당 계산",
    UNLIMITED: "제한 없음",
    FREE: "자유로운",
    MONTHLY: "월",
    TERMS_OF_SERVICE: "서비스 약관",
    PRIVACY_POLICY: "개인 보호 정책",
    CONTACT_EMAIL: "이메일 연락처:",

    SERVER_UNAVAILABLE: "서버에 현재 몇 가지 문제가 있습니다. 나중에 다시 시도해 주세요.",
    TASK_ALREADY_RUNNING: "한 번에 하나의 계산만 실행할 수 있습니다.",
    TOO_MANY_PANELS: "5000개 이상 주문 판재를 입력할 수 없습니다.",
    TOO_MANY_STOCK_PANELS: "5000개 이상 재고 판재를 입력할 수 없습니다.",
    LIMITS_REACHED: "계산 한도에 도달하였습니다. 이비오 개발팀에 문의해주세요.",
    OPEN_RUNNING_CALC: "실행 중인 계산 열기",

    ABOUT_MSG_1: "PECO는 목재 재단 최적화를 위한 프로그램입니다. 생성된 자투리를 자동 입력 관리할 수 있으며 재고 판재로 관리하여 최적화된 재단 패턴을 생성합니다.",
    ABOUT_MSG_2: "다양한 기능은 서버의 환경에 따라 계산이 제한될 수 있습니다. 해당 상황 발생 시 이비오 개발팀에 문의해주세요.",
    ABOUT_MSG_3: "해당 버전은 지속적인 업그레이드가 진행될 예정입니다.",
    SUBSCRIPTION_MSG_1: "지속적인 업그레이드를 위해 사용에 대한 피드백을 요청드립니다.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "업그레이드는 최대한 빠른 시일 내 반영할 수 있도록 노력하겠습니다.",
    SUBSCRIPTION_ADDITINAL_MSG_2: "업그레이드의 난이도에 따라 비용이 청구될 수 있습니다.",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "First monthly billing cycle begins on the day that you activate service",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "There are no refunds or credits for partial months",
    SUBSCRIPTION_ADDITINAL_MSG_5: "PECO는 언제나 고도화된 업그레이드를 진행합니다.",

    SUBSCRIPTION_INVOICE: "부가세와 관련된 견적서는 다음을 통해 요청될 수 있습니다.",

    TRY_WEB_MSG: "PECO는 웹사용을 기반으로 하며 빠른 계산을 제공하는 전용 서버를 사용합니다.: ",

    SAVED_ITEM_LIMIT_REACHED: "최대 허용 저장 항목 수에 도달했습니다.",
    SUBSCRIPTION_ACTIVE: "사용이 정상화되었습니다. 감사합니다.",
    SUBSCRIPTION_PLAN: "사용 계획",
    CONTRIBUTE: "기부",
    SUBSCRIBE: "구독",
    ACTIVE: "활성화",
    PER_DAY: "일일",
    CLIENT_STATS: "통계",
    ALLOWED_CALCULATIONS: "허용된 계산",
    CALCULATION_SPEED: "계산 속도",
    SAVED_ITEMS: "저장 항목",
    PRICE: "가격",
    GOLD: "골드",
    SILVER: "실버",

    DIMENSIONS_TO_LABELS: "비고 란에 치수 입력",
    REPLACE_LABELS_QUESTION: "비고 란을 변경하시겠습니까?",

    WHATS_NEW: "새로운 소식",

    FILENAME: "파일명",
    FONT_SIZE: "글자 크기",
    BIG: "크게",
    HUGE: "더 크게",
    SEARCH: "탐색",
    RENAME: "이름 바꾸기",
    RENAMED: "이름 바꾸기",
    SAVE: "저장",

    PDF_HEADER_TEXT: "머리말",
    PDF_ADDITIONAL_TEXT: "추가 문구",
    PDF_SHOW_SUMMARY: "요약 보기",
    PDF_SHOW_DATE: "날짜 보기",
    PDF_SHOW_CUTS_TABLE: "재단 표 보기",

    UNSAVED_CHANGES: "저장하지 않은 변경 사항은 손실됩니다. 계속 진행하시겠습니까?",
    ALREADY_EXISTS: "이미 존재함",

    GENERIC_ERROR_MSG: "오류가 발생했습니다.",

    PRO_FEATURE: "프리미엄 기능",
    PRO_FEATURES: "프리미엄 기능",

    CUT_ORIENTATION_PREFERENCE: "재단 방향",
    CUT_ORIENTATION_PREFERENCE_NONE: "나뭇결 고려 없음",
    CUT_ORIENTATION_PREFERENCE_WIDTH: "폭 방향 나뭇결 고려",
    CUT_ORIENTATION_PREFERENCE_LENGTH: "길이 방향 나뭇결 고려",

    SUPPORT_PRIORITY: "우선 지원",
    MEDIUM: "중간",

    FORCE_SERVER_SIDE_CALC: "전용 서버에서 계산 실행",
    ANDROID_PRO_VERSION: "안드로이드 프로 앱",

    NO_ADS: "광고 없음",
    SUBSCRIPTION_REQUEST: "이 기능을 사용하려면 계정 설정이 수정되어야 합니다.",
    UPGRADE_PLAN: "업그레이드",

    SUBSCRIPTION_APLICABLE: "계정 설정을 통해 계정의 기능을 해제할 수 있습니다.",
    SUBSCRIPTION_FEATURES_DEVICE: "계정 설정을 통해 계정의 기능을 모든 장치에서 사용할 수 있습니다.",

    CANCEL_SUBSCRIPTION: "구독 활성화를 취소하시겠습니까?",
    SUBSCRIPTION_CANCELED: "구독 취소",
    SUBSCRIPTION_CANCEL_ERROR: "문제가 발생했습니다. 나중에 다시 시도해주세요. 지속적인 문제 발생 시 이비오 개발팀에 문의해주세요.",
    MANAGE_SUBSCRIPTION: "구독 관리",

    MINIMUM_TRIM_DIMENSION: "최소 트림 치수",
    GROUP_EQUAL_MOSAICS: "재고 판재와 동일한 주문 판재",
    AUTO: "자동",
    NEVER: "절대",
    ALWAYS: "항상",

    SURPLUS: "여분",
    RESULT: "결과",


    ADDRESS: "주소",
    CITY: "도시",
    ZIP_CODE: "우편번호",
    COUNTRY: "국가",
    VAT: "부가세 번호",
    BILLING_EMAIL: "고지서 이메일",

    SHOULD_SEND_INVOICE: "이메일로 견적 받기",
    BILLING_DETAILS: "결제 세부 정보",
    PAYPAL_BILLING_DETAILS_MSG: "페이팔 청구 세부정보는 인보이스 발행에 사용됩니다.",

    PERMIT_PERIOD_ADDITINAL_MSG_1: "일회성 요금제는 실버 요금제와 기능이 동일합니다.",
    PERMIT_PERIOD_ADDITINAL_MSG_2: "요금제 기능은 결제 후 즉시 사용 가능합니다.",
    PERMIT_PERIOD_ADDITINAL_MSG_3: "저장된 데이터는 요금제가 만료된 후에도 항상 불러올 수 있습니다.",

    PERMIT_PERIOD_ACTIVE: "계정이 활성화되었습니다. 감사합니다.",

    WIDTH_1ST: "치수 주문",

    PANELS_HELPER_TEXT: "잘라낼 조각",
    STOCK_PANELS_HELPER_TEXT: "잘라낼 시트"
};
