// Ukrainian
var translationsUA = {
    TITLE: "CutList Optimizer",
    PRO_VERSION: "Про версія",
    PANEL: "Плита",
    PANELS: "Плити",
    STOCK_PANEL: "запасний аркуш",
    STOCK: "Склад",
    WIDTH: "Ширина",
    HEIGHT: "Довжина",
    QUANTITY: "Кількість",
    LABEL: "Етикетка",
    CUT: "Пропил",
    CUTS: "Пропили",
    TOTAL_CUTS_NBR: "Загальні скорочення",
    CUT_LENGTH: "Вирізати довжину",
    TOTAL_CUT_LENGTH: "Загальна роздрукована довжина",
    DIM: "величина",
    USED_AREA: "Використана площа",
    TOTAL_USED_AREA: "Загальна використовувана площа",
    WASTED_AREA: "Залишок",
    TOTAL_WASTED_AREA: "Загальна втрачена площа",
    WASTED_PANELS: "Відходи",
    STATS: "Глобальна статистика",
    SHEET_STATISTICS: "Статистика листа",
    NBR_MOSAICS: "Використовувані фонди",
    UNABLE_TO_FIT: "Не вдалося встановити",
    CUT_THICKNESS: "Товщина пропилу",

    NAME: "Ім'я",
    NONE: "Немає",
    CALCULATE: "Порахувати",
    ACCEPT: "Прийняти",
    CANCEL: "Віміна",
    ERROR: "Помилка",
    OPTIONS: "Опції",
    SETTINGS: "Налаштування",
    LANGUAGE: "Мова",
    ENABLE: "Enable",
    DISABLE: "Disable",
    ENABLED: "Увімкнено",
    DISABLED: "Інваліди",
    REMOVE: "Remove",
    REMOVED: "Вилучено",
    LOW: "Низький",
    NORMAL: "Нормальний",
    HIGH: "Високий",
    UPGRADE: "Оновити",
    ABOUT: "Про",
    DELETE: "Видалити",
    SAVED: "Збережено",
    DELETED: "Видалено",
    LOADED: "Завантажений",
    LOGOUT: "Вийти",
    ADD_NEW: "Додати новий",

    ADD_LINE: "Додати рядок",
    LOAD: "Завантаження",
    SAVE_LIST: "Зберегти",
    ENABLE_DISABLE_ALL: "Увімкнути / вимкнути всіх",
    DELETE_ALL: "Очистити все",
    EXPORT_CSV: "Експорт до CSV",
    IMPORT_CSV: "Імпорт з CSV",
    CLEAR_LIST: "Чіткий перелік?",
    RESET_DATA: "Новий порожній проект",

    EMAIL: "Електронна пошта",
    PASSWORD: "Пароль",
    CONFIRM_PASSWORD: "Підтвердьте пароль",
    SIGN_IN: "Увійти",
    SIGN_OUT: "Вийти з аккаунта",
    SIGN_UP: "Зареєструйтесь",
    OR: "або",
    SIGN_IN_GOOGLE: "Увійдіть у Google",
    FORGOT_PASS: "Забули свій пароль?",
    PASS_RESET: "Скидання пароля",
    PASS_RESET_MSG: "Будь ласка, введіть свій електронний лист. Ви отримаєте посилання для створення нового пароля.",
    PASS_SAVE_MSG: "Введіть новий пароль.",
    LOGIN_REQUEST: "Будь ласка, увійдіть спочатку",

    PDF_PAGE: "сторінки",
    REPORT_AN_ISSUE: "Повідомте про проблему",
    OPTIMIZATION_PRIORITY: "Пріоритет оптимізації",
    LEAST_WASTED_AREA: "Найменш впущена територія",
    LEAST_NUMBER_OF_CUTS: "Найменша кількість скорочень",

    ZOOM_IN: "Приближувати",
    ZOOM_OUT: "Зменшення",
    INCREASE_FONT_SIZE: "Збільшити розмір шрифту",
    DECREASE_FONT_SIZE: "Зменшити розмір шрифту",
    RESET_ZOOM: "Скидання перегляду",
    ROTATE_90: "Поворот на 90º",
    PANEL_LABELS: "Наклейки на панелі",
    COLORED_PANELS: "Заповнені кольорові панелі",
    SHOW_CUTS: "Порядок скорочень",
    SHOW_DIMENSIONS: "Розміри",

    SAVE_PROJECT: "Зберегти проект",
    LOAD_PROJECT: "Завантажити проект",
    NO_SAVED_DATA: "Збережених даних немає",
    OVERWRITE: "Перепишіть",
    SAVE_AS: "Зберегти як",
    ALREADY_EXISTS: "Вже існує",

    INITIALIZING: "Ініціалізація",
    COMPUTING: "Розрахунок...",
    SEARCHING_BEST: "Пошук найкращого рішення",
    EXPORT_PDF: "Експорт в PDF",
    EXPORT_IMG: "Експортувати до зображення",
    EXPORTING_PDF: "Exporting to PDF...",
    EXPORTING_IMG: "Exporting to image...",
    NOTHING_TO_EXPORT: "Нічого не експортувати",
    CLICK_TO_ACCEPT: "Click to accept solution",
    TAP_TO_ACCEPT: "Tap to accept solution",
    MSG_NO_PANELS: "Не вказано жодних плит",
    MSG_NO_STOCK_PANELS: "Не вказано запасних плит",
    // TODO: OPTIMIZATION_LEVEL: "Рівень оптимізації",
    IMAGE_PAN_ZOOM: "Увімкнути панель зображень та збільшити",
    FORCE_ONE_STOCK_PANEL: "Використовуйте лише одну плиту із складу",

    UNITS: "Одиниці",
    DECIMAL_PLACES: "Десяткові місця",
    GENERIC: "Родовий (16,5)",
    MM: "Міліметри (16.5 mm)",
    CM: "Сантиметри (16.5 cm)",
    INCHES: "Дюйми (16.5\")",
    FEET_INCHES: "Десяткові фути і дюйми (1' 4.5\")",
    FEET_INCHES_FRAC: "Дробові фути та дюйми (1' 4 1/2\")",
    INCHES_FRAC: "Дробові дюйми (16 1/2\")",

    MATERIAL: "Матеріал",
    CREATE_MATERIAL: "Створіть новий тип матеріалу",
    MSG_NO_STOCK_MATERIAL: "Немає в наявності складського аркуша необхідного матеріалу",
    CONSIDER_MATERIALS: "Розглянемо матеріал",

    EDGE_BANDING: "Обклеювання краю",
    EDGE_BAND: "Крайова смуга",
    TOP_EDGE_BAND: "Діапазон верхнього краю",
    LEFT_EDGE_BAND: "Ліва стрічка",
    BOTTOM_EDGE_BAND: "Нижній край стрічки",
    RIGHT_EDGE_BAND: "Правий край смуги",
    CREATE_EDGE_BAND: "Створіть новий тип крайової смуги",

    ORIENTATION_MATTERS: "Розглянемо напрямок зерна",
    NO_GRAIN: "Жодного зернового розгляду",
    HORIZONTAL_GRAIN: "Зерно по ширині",
    VERTICAL_GRAIN: "Зерно по довжині",

    CALCULATIONS_PER_WEEK: "Розрахунки на тиждень",
    UNLIMITED: "необмежений",
    FREE: "безкоштовно",
    MONTHLY: "щомісяця",
    TERMS_OF_SERVICE: "Умови обслуговування",
    PRIVACY_POLICY: "Політика конфіденційності",
    CONTACT_EMAIL: "Контактна електронна пошта:",

    SERVER_UNAVAILABLE: "Наразі сервер має деякі проблеми. Повторіть спробу пізніше.",
    TASK_ALREADY_RUNNING: "Одночасно дозволяється запускати лише один розрахунок",
    TOO_MANY_PANELS: "Неможливо виконати розрахунок з більш ніж 1000 панелями",
    TOO_MANY_STOCK_PANELS: "Неможливо виконати розрахунок з більш ніж 1000 запасів",
    LIMITS_REACHED: "Досягнуто вашого безкоштовного щоденного ліміту розрахунку. Будь ласка, подумайте про підтримку розвитку.",
    OPEN_RUNNING_CALC: "Відкрити запущений розрахунок",

    ABOUT_MSG_1: "CutList Optimizer - це програма, орієнтована на оптимізацію різання панелей. Він створює оптимізовані шаблони різання на основі наявних запасів, вкладаючи необхідні деталі.",
    ABOUT_MSG_2: "Усі функції повністю доступні безкоштовно протягом обмеженої кількості розрахунків на тиждень.",
    ABOUT_MSG_3: "Якщо ви вважаєте, що ця програма є корисною, будь ласка, подумайте про оновлення до версії Pro, щоб підтримати її розвиток. Крім того, ви можете оновити свій обліковий запис на веб-сайті, і ви отримаєте доступ як до версії Android Pro, так і до преміум-функцій веб-сайту.",
    SUBSCRIPTION_MSG_1: "Зробіть свій внесок у оптимізатор CutList, перейшовши на версію Pro.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "Підписка набирає чинності негайно",
    SUBSCRIPTION_ADDITINAL_MSG_2: "З вашого рахунку PayPal стягуватиметься плата автоматично на початку кожного платіжного циклу",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "Перший щомісячний платіжний цикл починається з дня активації послуги",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "Повернення коштів або кредитів за часткові місяці немає",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Ви можете скасувати підписку в будь-який час у своєму обліковому записі PayPal і можете продовжувати користуватися послугою до закінчення рахунку",

    TRY_WEB_MSG: "Оптимізатор CutList також доступний в Інтернеті. Веб-версія пропонує оптимізовані функції та використовує спеціалізований сервер, що забезпечує швидші обчислення: "
};
