// Portuguese
var translationsPT= {
    TITLE: "CutList Optimizer",
    PRO_VERSION: "Versão Pro",
    PANEL: "Painel",
    PANELS: "Painéis",
    STOCK_PANEL: "Painel de stock",
    STOCK: "Stock",
    WIDTH: "Largura",
    HEIGHT: "Comprimento",
    QUANTITY: "Qtd",
    LABEL: "Nome",
    CUT: "Corte",
    CUTS: "Cortes",
    TOTAL_CUTS_NBR: "Cortes totais",
    CUT_LENGTH: "Comprimento de corte",
    TOTAL_CUT_LENGTH: "Comprimento de corte total",
    DIM: "Dim",
    USED_AREA: "Área utilizada",
    TOTAL_USED_AREA: "Área total utilizada",
    WASTED_AREA: "Área excedente",
    TOTAL_WASTED_AREA: "Área total desperdiçada",
    WASTED_PANELS: "Excedentes",
    STATS: "Estatísticas",
    SHEET_STATISTICS: "Estatísticas do painel",
    NBR_MOSAICS: "Painéis de stock utilizados",
    UNABLE_TO_FIT: "Paineis em falta",
    CUT_THICKNESS: "Espessura de corte",

    NAME: "Nome",
    NONE: "Nenhum",
    CALCULATE: "Calcular",
    ACCEPT: "Aceitar",
    CANCEL: "Cancelar",
    ERROR: "Erro",
    OPTIONS: "Opções",
    SETTINGS: "Definições",
    LANGUAGE: "Língua",
    ENABLE: "Ativar",
    DISABLE: "Desativar",
    ENABLED: "Ativado",
    DISABLED: "Desativado",
    REMOVE: "Remove",
    REMOVED: "Removido",
    LOW: "Baixo",
    NORMAL: "Normal",
    HIGH: "Alto",
    UPGRADE: "Upgrade",
    ABOUT: "Sobre",
    DELETE: "Eliminar",
    SAVED: "Guardado",
    DELETED: "Eliminado",
    LOADED: "Carregado",
    LOGOUT: "Sair",
    ADD_NEW: "Adicionar novo",

    ADD_LINE: "Adicionar linha",
    LOAD: "Carregar",
    SAVE_LIST: "Guardar",
    ENABLE_DISABLE_ALL: "Ativar / desativar todos",
    DELETE_ALL: "Eliminar todos",
    EXPORT_CSV: "Exportar para CSV",
    IMPORT_CSV: "Importar de CSV",
    CLEAR_LIST: "Limpar lista?",
    RESET_DATA: "Novo projeto em branco",

    EMAIL: "Email",
    PASSWORD: "Senha",
    CONFIRM_PASSWORD: "Confirme a Senha",
    SIGN_IN: "Sign In",
    SIGN_OUT: "Sair",
    SIGN_UP: "Criar conta",
    OR: "ou",
    SIGN_IN_GOOGLE: "Login com o Google",
    FORGOT_PASS: "Esqueceu sua senha?",
    PASS_RESET: "Redefinição de senha",
    PASS_RESET_MSG: "Por favor introduza o seu e-mail. Você receberá um link para criar uma nova senha.",
    PASS_SAVE_MSG: "Digite a sua nova senha.",
    LOGIN_REQUEST: "Faça login primeiro",

    PDF_PAGE: "página",
    REPORT_AN_ISSUE: "Reportar um problema",
    OPTIMIZATION_PRIORITY: "Prioridade de otimização",
    LEAST_WASTED_AREA: "Menor área desperdiçada",
    LEAST_NUMBER_OF_CUTS: "Menor número de cortes",

    ZOOM_IN: "Ampliar",
    ZOOM_OUT: "Diminuir",
    INCREASE_FONT_SIZE: "Aumentar o tamanho da fonte",
    DECREASE_FONT_SIZE: "Diminuir tamanho da fonte",
    RESET_ZOOM: "Repor vista",
    ROTATE_90: "Girar 90º",
    PANEL_LABELS: "Nome nos painéis",
    COLORED_PANELS: "Preenchimento com cor",
    SHOW_CUTS: "Ordem dos cortes",
    SHOW_DIMENSIONS: "Dimensões",

    SAVE_PROJECT: "Guardar projeto",
    LOAD_PROJECT: "Carregar projeto",
    NO_SAVED_DATA: "Nenhum dado guardado",
    OVERWRITE: "Substituir",
    SAVE_AS: "Guardar como",
    ALREADY_EXISTS: "Já existe",

    INITIALIZING: "Inicializando",
    COMPUTING: "Calculando...",
    SEARCHING_BEST: "Procurando a melhor solução",
    EXPORT_PDF: "Exportar para PDF",
    EXPORT_IMG: "Exportar para imagem",
    EXPORTING_PDF: "Exporting to PDF...",
    EXPORTING_IMG: "Exporting to image...",
    NOTHING_TO_EXPORT: "Nada para exportar",
    CLICK_TO_ACCEPT: "Click to accept solution",
    TAP_TO_ACCEPT: "Tap to accept solution",
    MSG_NO_PANELS: "Não foram especificados painéis.",
    MSG_NO_STOCK_PANELS: "Não foram especificado painéis em stock.",
    // TODO: OPTIMIZATION_LEVEL: "Nível de otimização",
    IMAGE_PAN_ZOOM: "Ativar zoom da imagem",
    FORCE_ONE_STOCK_PANEL: "Utilizar apenas uma unidade de stock",

    UNITS: "Unidades",
    DECIMAL_PLACES: "Casas decimais",
    GENERIC: "Genérico (16.5)",
    MM: "Milímetros (16,5 mm)",
    CM: "Centímetros (16,5 cm)",
    INCHES: "Polegadas (16,5 \")",
    FEET_INCHES: "Pés decimais e polegadas (1 '4,5 \")",
    FEET_INCHES_FRAC: "Pés e polegadas fracionários (1 '4 1/2 \")",
    INCHES_FRAC: "Polegadas fracionárias (16 1/2 \")",

    MATERIAL: "Material",
    CREATE_MATERIAL: "Criar novo tipo de material",
    MSG_NO_STOCK_MATERIAL: "Nenhuma folha de estoque disponível do material necessário",
    CONSIDER_MATERIALS: "Considere material",

    EDGE_BANDING: "Borda de borda",
    EDGE_BAND: "Banda de borda",
    TOP_EDGE_BAND: "Banda da borda superior",
    LEFT_EDGE_BAND: "Banda da borda esquerda",
    BOTTOM_EDGE_BAND: "Banda da borda inferior",
    RIGHT_EDGE_BAND: "Banda da borda direita",
    CREATE_EDGE_BAND: "Crie um novo tipo de banda de borda",

    ORIENTATION_MATTERS: "Considere a direção do grão",
    NO_GRAIN: "Sem consideração de grãos",
    HORIZONTAL_GRAIN: "Grão ao longo da largura",
    VERTICAL_GRAIN: "Grão ao longo do comprimento",

    CALCULATIONS_PER_WEEK: "Cálculos por semana",
    UNLIMITED: "ilimitado",
    FREE: "Grátis",
    MONTHLY: "por mês",
    TERMS_OF_SERVICE: "Termos de serviço",
    PRIVACY_POLICY: "Política de Privacidade",
    CONTACT_EMAIL: "Email de contato:",

    SERVER_UNAVAILABLE: "No momento, o servidor está com alguns problemas. Tente novamente mais tarde.",
    TASK_ALREADY_RUNNING: "Apenas um cálculo pode ser executado de uma vez",
    TOO_MANY_PANELS: "Não é possível executar o cálculo com mais de 1000 painéis",
    TOO_MANY_STOCK_PANELS: "Não é possível executar o cálculo com mais de 1000 folhas de estoque",
    LIMITS_REACHED: "Seu limite de cálculo diário gratuito foi atingido. Por favor, considere apoiar o desenvolvimento.",
    OPEN_RUNNING_CALC: "Cálculo de execução aberto",

    ABOUT_MSG_1: "O CutList Optimizer é um aplicativo direcionado à otimização de corte de painéis. Ele gera padrões de corte otimizados com base nas folhas de estoque disponíveis, aninhando as peças necessárias.",
    ABOUT_MSG_2: "Todos os recursos estão totalmente disponíveis gratuitamente, dentro de um número limitado de cálculos por semana.",
    ABOUT_MSG_3: "Se você achar este aplicativo útil, considere atualizar para a versão Pro para apoiar seu desenvolvimento. Como alternativa, você pode atualizar sua conta no site e terá acesso aos recursos da versão Android Pro e do site premium.",
    SUBSCRIPTION_MSG_1: "Contribua para o CutList Optimizer, atualizando para a versão Pro.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "A assinatura entrará em vigor imediatamente",
    SUBSCRIPTION_ADDITINAL_MSG_2: "Sua conta do PayPal será cobrada automaticamente no início de cada ciclo de faturamento",
    // SUBSCRIPTION_ADDITINAL_MSG_3: "O primeiro ciclo de cobrança mensal começa no dia em que você ativa o serviço",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "Não há reembolsos ou créditos para meses parciais",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Você pode cancelar sua assinatura a qualquer momento em sua conta do PayPal e continuar usando o serviço até o término do período de cobrança",

    TRY_WEB_MSG: "O CutList Optimizer também está disponível na web. A versão Web oferece recursos otimizados e utiliza um servidor dedicado, fornecendo cálculos mais rápidos: "
};
