// Bulgarian
var translationsBG = {

    TITLE: "CutList Optimizer",
    PRO_VERSION: "Версия Про",
    PANEL: "Детайл",
    PANELS: "Детайли",
    STOCK_PANEL: "Материал",
    STOCK: "Материал",
    WIDTH: "Широчина",
    HEIGHT: "Дължина",
    QUANTITY: "Кол-во",
    LABEL: "Название",
    CUT: "Разрез",
    CUTS: "Разрез",
    TOTAL_CUTS_NBR: "Общо Разрези",
    CUT_LENGTH: "Дължина на разреза",
    TOTAL_CUT_LENGTH: "Обща дължина на разрезите",
    DIM: "Размер",
    USED_AREA: "Използвана площ",
    TOTAL_USED_AREA: "Общо Използвана пл.",
    WASTED_AREA: "Неизползвана площ",
    TOTAL_WASTED_AREA: "Общо Неизползвана пл.",
    WASTED_PANELS: "Отпадък",
    STATS: "Общи данни",
    SHEET_STATISTICS: "Данни за плоскости",
    NBR_MOSAICS: "Използван материал",
    UNABLE_TO_FIT: "Не се вмества",
    CUT_THICKNESS: "Дебелина на разреза / ножа / прореза",

    NAME: "Название",
    NONE: "Незададено",
    CALCULATE: "Оразмери",
    ACCEPT: "Приеми",
    CANCEL: "Откажи",
    ERROR: "Грешка",
    OPTIONS: "Опции",
    SETTINGS: "Настройки",
    LANGUAGE: "Език",
    ENABLE: "Използвай",
    DISABLE: "Не Използвай",
    ENABLED: "Използва се",
    DISABLED: "Не се използва",
    REMOVE: "Изтрий",
    REMOVED: "Изтрито",
    LOW: "Низък",
    NORMAL: "Среден",
    HIGH: "Висок",
    UPGRADE: "Надгради",
    ABOUT: "За",
    DELETE: "Изтрий",
    SAVED: "Записан",
    DELETED: "Изтрит",
    LOADED: "Зареден",
    LOGOUT: "Излез",
    ADD_NEW: "Добави нов",

    ADD_LINE: "Добави нов ред",
    LOAD: "Зареди списък",
    SAVE_LIST: "Запиши списъка",
    ENABLE_DISABLE_ALL: "Включи / Изключи всичко",
    DELETE_ALL: "Изтрий всички",
    EXPORT_CSV: "Експорт в CSV",
    IMPORT_CSV: "Импорт от CSV",
    CLEAR_LIST: "Да се изчисти?",
    RESET_DATA: "Нов празен проeкт",

    EMAIL: "Имейл",
    PASSWORD: "Парола",
    CONFIRM_PASSWORD: "Потвърдете Паролата",
    SIGN_IN: "Влизане",
    SIGN_OUT: "Отписване",
    SIGN_UP: "Регистрация",
    OR: "или",
    SIGN_IN_GOOGLE: "Влезте през Google",
    FORGOT_PASS: "Забравихте си паролата?",
    PASS_RESET: "Ресет на паролата",
    PASS_RESET_MSG: "Моля, въведете си Имейла. Ще получите линк за създаване на нова парола.",
    PASS_SAVE_MSG: "Моля, въведете новата си парола.",
    LOGIN_REQUEST: "Моля, първо влезте",

    PDF_PAGE: "страница",
    REPORT_AN_ISSUE: "Съобщете за проблема",
    OPTIMIZATION_PRIORITY: "Предпочитана оптимизацията",
    LEAST_WASTED_AREA: "По-малко отпадък",
    LEAST_NUMBER_OF_CUTS: "По-малко разрези",

    ZOOM_IN: "Приближи",
    ZOOM_OUT: "Намали",
    INCREASE_FONT_SIZE: "Увеличи шрифта",
    DECREASE_FONT_SIZE: "Намали  шрифта",
    RESET_ZOOM: "Ресет на Изгледа",
    ROTATE_90: "Завърти на 90?",
    PANEL_LABELS: "Названия на плоскостите",
    COLORED_PANELS: "Десен на плоскостите",
    SHOW_CUTS: "Порядък на разрязване",
    SHOW_DIMENSIONS: "Габарити",

    SAVE_PROJECT: "Запиши проeкта",
    LOAD_PROJECT: "Зареди проeкт",
    NO_SAVED_DATA: "Няма записани данни",
    OVERWRITE: "Презапиши",
    SAVE_AS: "Запиши като",
    ALREADY_EXISTS: "Вече съществува",

    INITIALIZING: "Инициализация",
    COMPUTING: "Пресмята",
    SEARCHING_BEST: "Търсене за оптимално решение",
    EXPORT_PDF: "Експорт в PDF",
    EXPORT_IMG: "Експорт в изображение",
    EXPORTING_PDF: "Създава PDF",
    EXPORTING_IMG: "Създава изображение",
    NOTHING_TO_EXPORT: "Няма за експортиране",
    CLICK_TO_ACCEPT: "Щракнете за приемане на решение",
    TAP_TO_ACCEPT: "Докоснете за приемане на решение",
    MSG_NO_PANELS: "Не уточнихте плоскостите",
    MSG_NO_STOCK_PANELS: "Незададени листове наличности",
    // TODO: OPTIMIZATION_LEVEL: "Optimization level",
    IMAGE_PAN_ZOOM: "Заключи Пропорции & Увеличение",
    FORCE_ONE_STOCK_PANEL: "Използвай само един лист материал",

    UNITS: "Единици",
    DECIMAL_PLACES: "Десетични знаци",
    GENERIC: "Общи (16.5)",
    MM: "Милиметри (16.5 mm)",
    CM: "Сантиметри (16.5 cm)",
    INCHES: "Инчове (16.5\")",
    FEET_INCHES: "Десетични стъпки & Инчове (1' 4.5\")",
    FEET_INCHES_FRAC: "Дроби & Инчове (1' 4 1/2\")",
    INCHES_FRAC: "Дробни инчове (16 1/2\")",

    MATERIAL: "Материал",
    CREATE_MATERIAL: "Създай нов тип материал",
    MSG_NO_STOCK_MATERIAL: "Няма материал от дадения тип",
    CONSIDER_MATERIALS: "Уточни материала",

    EDGE_BANDING: "Oкантване",
    EDGE_BAND: "Кант",
    TOP_EDGE_BAND: "Кант горен",
    LEFT_EDGE_BAND: "Кант ляв",
    BOTTOM_EDGE_BAND: "Кант долен",
    RIGHT_EDGE_BAND: "Кант десен",
    CREATE_EDGE_BAND: "Създай нов тип Кант",

    ORIENTATION_MATTERS: "Уточни посока на текстура",
    NO_GRAIN: "Игнорирай текстурата",
    HORIZONTAL_GRAIN: "Хоризонтална текстура",
    VERTICAL_GRAIN: "Вертикална текстура",

    CALCULATIONS_PER_WEEK: "Разкрояване за седмица",
    UNLIMITED: "неограничено",
    FREE: "Безплатен",
    MONTHLY: "месечно",
    TERMS_OF_SERVICE: "Условия на обслуживане",
    PRIVACY_POLICY: "Политика на конфиденциалност",
    CONTACT_EMAIL: "Имейл за контакт:",

    SERVER_UNAVAILABLE: "В дадения момент сървъре е недостъпен. Пробвайте по-късно.",
    TASK_ALREADY_RUNNING: "Едновременно може да извършва само едно разкрояване.",
    TOO_MANY_PANELS: "Невъзможно е да разкроява повече от 1000 плота",
    TOO_MANY_STOCK_PANELS: "Невъзможно е да разкроява повече от 1000 листа",
    LIMITS_REACHED: "Вашия безплатен дневен лимит за разкрояване свърши. Моля, помислете за подкрепа на проекта.",
    OPEN_RUNNING_CALC: "Отворено пресмятане",

    ABOUT_MSG_1: "Програмата CutList Optimizer е за оптимизация при разкрояване на плоскости.",
    ABOUT_MSG_2: "Проектира плана за нарязване използвайки достъпния материал по-оптимално.",
    ABOUT_MSG_3: "Ако считате приложението за полезно, разгледайте възможността за обновяване до версия Pro за подкрепа на разработката му. Освен това, може да обновите профила си на веб-сайта, и ще имате достъп както до версия Android Pro, така и до допълнителни функции на веб-сайта.",
    SUBSCRIPTION_MSG_1: "Допринесете за CutList Optimizer, обновявайки се до версия Pro.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "Абонамента встъпва в сила веднага",
    SUBSCRIPTION_ADDITINAL_MSG_2: "От вашата сметка в PayPal ще се изтегля сума в началото на всеки платежен цикъл.",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "First monthly billing cycle begins on the day that you activate service",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "There are no refunds or credits for partial months",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Може да отмените абонамента си когато пожелаете от профила си в PayPal, и може да продължите да ползвате това обслужване до завършване на заплатения срок",

    SUBSCRIPTION_INVOICE: "Фактура за ДДС може да бъде поискана чрез ",

    TRY_WEB_MSG: "CutList Optimizer също е достъпен и в Интернет. Веб-версията предоставя оптимизиращи функции и използва определен сървър, осигуряващ по-бързи изчисления: ",

    SAVED_ITEM_LIMIT_REACHED: "Достигнат Максимален брой записани елементи",
    SUBSCRIPTION_ACTIVE: "Вашият абонамент е активен",
    SUBSCRIPTION_PLAN: "Абонаментен план",
    CONTRIBUTE: "Участвайте",
    SUBSCRIBE: "Абонамент",
    ACTIVE: "Активен",
    PER_DAY: "за ден",
    CLIENT_STATS: "Статистика",
    ALLOWED_CALCULATIONS: "Разрешени пресмятания",
    CALCULATION_SPEED: "Скорост на пресмятания",
    SAVED_ITEMS: "Записани елементи",
    PRICE: "Цена",
    GOLD: "Златен",
    SILVER: "Сребърен",

    DIMENSIONS_TO_LABELS: "Попълнете полетата с размери",
    REPLACE_LABELS_QUESTION: "Да замени ли дадените полета?",

    WHATS_NEW: "Какво ново",

    FILENAME: "Название",
    FONT_SIZE: "Размер на Шрифта",
    BIG: "Голям",
    HUGE: "Огромен",
    SEARCH: "Търси",
    RENAME: "Преименувай",
    RENAMED: "Преименувано",
    SAVE: "Запиши",

    PDF_HEADER_TEXT: "Заглавен текст",
    PDF_ADDITIONAL_TEXT: "Допълнителен текст",
    PDF_SHOW_SUMMARY: "Покажи Общо",
    PDF_SHOW_DATE: "Покажи дата",
    PDF_SHOW_CUTS_TABLE: "Покажи таблица на разрези",

    UNSAVED_CHANGES: "Всяка незаписана промяна ще се изгуби. Продължавате?",
    ALREADY_EXISTS: "вече съществува!",

    GENERIC_ERROR_MSG: "Възникна грешка!",

    PRO_FEATURE: "Premium функция",
    PRO_FEATURES: "Premium функции",

    CUT_ORIENTATION_PREFERENCE: "Разрезна ориентация",
    CUT_ORIENTATION_PREFERENCE_NONE: "Оптимална",
    CUT_ORIENTATION_PREFERENCE_WIDTH: "Разрязване по широчина",
    CUT_ORIENTATION_PREFERENCE_LENGTH: "Разрязване по дължина",

    SUPPORT_PRIORITY: "Приоритетна поддръжка",
    MEDIUM: "Средна",

    FORCE_SERVER_SIDE_CALC: "Направи пресмятания на специалния сървър",
    ANDROID_PRO_VERSION: "Android Pro app",

    NO_ADS: "Без реклами",
    SUBSCRIPTION_REQUEST: "Тази опция изисква профил с активиран абонаментен план",
    UPGRADE_PLAN: "Надгради профилния абонамент",

    SUBSCRIPTION_APLICABLE: "Абонамента важи и за Уебсайта и за Андроид приложението, отключвайки всички функции за профила",
    SUBSCRIPTION_FEATURES_DEVICE: "Абонаментните функции и записани данни ще са ви достъпни на всяко устройство след влизане в профила.",

    CANCEL_SUBSCRIPTION: "Наистина ли искате да анулирате активния си абонамент?",
    SUBSCRIPTION_CANCELED: "Абонаментът е прекратен",
    SUBSCRIPTION_CANCEL_ERROR: "Нещо се обърка, моля опитайте отново по-късно. Можете също да анулирате абонамента си в PayPal с имейл до support@cutlistoptimizer.com",
    MANAGE_SUBSCRIPTION: "Управление на абонамента",

    MINIMUM_TRIM_DIMENSION: "Минимален брой разрези",
    GROUP_EQUAL_MOSAICS: "Стак панели със същото оформление",
    AUTO: "Автоматичен",
    NEVER: "Никога",
    ALWAYS: "Винаги",

    SURPLUS: "остатък",
    RESULT: "Резултат",


    ADDRESS: "Адрес",
    CITY: "Град",
    ZIP_CODE: "Пощенски / Zip Код",
    COUNTRY: "Страна",
    VAT: "Данъчен / ДДС номер",
    BILLING_EMAIL: "Имейл за фактуриране",

    SHOULD_SEND_INVOICE: "Получаване на ДДС фактура по имейл",
    BILLING_DETAILS: "Детайли за фактуриране",
    PAYPAL_BILLING_DETAILS_MSG: "Подробно фактуриране по PayPal ще бъдат използвани за фактури"
};
