// French
var translationsFR = {

    TITLE: "CutList Optimizer",
    PRO_VERSION: "Version Pro",
    PANEL: "Panneau",
    PANELS: "Panneaux",
    STOCK_PANEL: "Panneau en stock",
    STOCK: "Stock de paneaux",
    WIDTH: "Largeur",
    HEIGHT: "Longueur",
    QUANTITY: "Qté",
    LABEL: "Etiquette",
    CUT: "Coupe",
    CUTS: "Coupes",
    TOTAL_CUTS_NBR: "Nb de coupes",
    CUT_LENGTH: "Longueur de coupe",
    TOTAL_CUT_LENGTH: "Longueur de coupe totale",
    DIM: "Dim",
    USED_AREA: "Surface utilisée",
    TOTAL_USED_AREA: "Surface totale utilisée",
    WASTED_AREA: "Surface de chute",
    TOTAL_WASTED_AREA: "Surface totale de chutes",
    WASTED_PANELS: "Panneaux perdus",
    STATS: "Statistiques globales",
    SHEET_STATISTICS: "Statistiques panneau",
    NBR_MOSAICS: "Panneaux en stock utilisés",
    UNABLE_TO_FIT: "Adaptation impossible",
    CUT_THICKNESS: "Largeur de coupe/de lame",

    NAME: "Nom",
    NONE: "Sans",
    CALCULATE: "Calcul",
    ACCEPT: "Accepter",
    CANCEL: "Annuler",
    ERROR: "Erreur",
    OPTIONS: "Options",
    SETTINGS: "Réglages",
    LANGUAGE: "Langue",
    ENABLE: "Activer",
    DISABLE: "Désactiver",
    ENABLED: "Activé",
    DISABLED: "Desactivé",
    REMOVE: "Retirer",
    REMOVED: "Retiré",
    LOW: "Faible",
    NORMAL: "Normal",
    HIGH: "Elevé",
    UPGRADE: "Mise à jour",
    ABOUT: "A propos",
    DELETE: "Effacer",
    SAVED: "Sauvegardé",
    DELETED: "Effacé",
    LOADED: "Chargé",
    LOGOUT: "Déconnecter",
    ADD_NEW: "Ajouter",

    ADD_LINE: "Nouvelle ligne",
    LOAD: "Charger liste",
    SAVE_LIST: "Sauver liste",
    ENABLE_DISABLE_ALL: "Activer/Désactiver tout",
    DELETE_ALL: "Effacer",
    EXPORT_CSV: "Exporter en CSV",
    IMPORT_CSV: "Importer depuis CSV",
    CLEAR_LIST: "Effacer liste ?",
    RESET_DATA: "Nouveau projet vide",

    EMAIL: "Email",
    PASSWORD: "Mot de passe",
    CONFIRM_PASSWORD: "Confirmer mot de passe",
    SIGN_IN: "Se connecter",
    SIGN_OUT: "Se déconnecter",
    SIGN_UP: "S'inscrire",
    OR: "ou",
    SIGN_IN_GOOGLE: "Connection avec Google",
    FORGOT_PASS: "Mot de passe oublié ?",
    PASS_RESET: "Réinitialiser mot de passe",
    PASS_RESET_MSG: "Saisissez votre Email pour recevoir un lien de réinitialisation",
    PASS_SAVE_MSG: "Veuillez saisir votre nouveau mot de passe",
    LOGIN_REQUEST: "Veuillez d'abord vous inscrire",

    PDF_PAGE: "Page",
    REPORT_AN_ISSUE: "Signaler un problème",
    OPTIMIZATION_PRIORITY: "Priorité d'optimisation",
    LEAST_WASTED_AREA: "Le moins de chute possible",
    LEAST_NUMBER_OF_CUTS: "Le moins de traits de coupe",

    ZOOM_IN: "Zoom in",
    ZOOM_OUT: "Zoom out",
    INCREASE_FONT_SIZE: "Augmenter police",
    DECREASE_FONT_SIZE: "Diminuer police",
    RESET_ZOOM: "Réintialiser vue",
    ROTATE_90: "Pivoter vue 90°",
    PANEL_LABELS: "Etiquette sur les panneaux",
    COLORED_PANELS: "Panneaux en couleur",
    SHOW_CUTS: "Ordre des coupes",
    SHOW_DIMENSIONS: "Dimensions",

    SAVE_PROJECT: "Enregistrer projet",
    LOAD_PROJECT: "Charger projet",
    NO_SAVED_DATA: "Aucune donnée enregistrée",
    OVERWRITE: "Ecraser",
    SAVE_AS: "Enregistrer sous",
    ALREADY_EXISTS: "Existe déjà",

    INITIALIZING: "En cours d'initialisation",
    COMPUTING: "Calcul en cours",
    SEARCHING_BEST: "Recherche de la meilleure solution",
    EXPORT_PDF: "Exporter en PDF",
    EXPORT_IMG: "Exporter comme image",
    EXPORTING_PDF: "Génération du PDF",
    EXPORTING_IMG: "Génération de l'image",
    NOTHING_TO_EXPORT: "Rien à exporter",
    CLICK_TO_ACCEPT: "Cliquer pour accepter la solution",
    TAP_TO_ACCEPT: "Touchez pour accepter la solution",
    MSG_NO_PANELS: "Aucun panneau spécifié",
    MSG_NO_STOCK_PANELS: "Aucun panneau en stock spécifié",
    IMAGE_PAN_ZOOM: "Verrouiller déplacement et zoomer",
    FORCE_ONE_STOCK_PANEL: "N'utiliser qu'un panneau du stock",

    UNITS: "Unités",
    DECIMAL_PLACES: "Decimales",
    GENERIC: "Génériques (16.5)",
    MM: "Millimètres (16.5mm)",
    CM: "Centimètres (16.5cm)",
    INCHES: "Pouces (16.5\")",
    FEET_INCHES: "Pieds et pouces décimaux (1' 4.5\")",
    FEET_INCHES_FRAC: "Pieds et pouces fraction (1' 4 1/2\")",
    INCHES_FRAC: "Pouces fraction (16 1/2\")",

    MATERIAL: "Matériau",
    CREATE_MATERIAL: "Créer un nouveau matériau",
    MSG_NO_STOCK_MATERIAL: "Pas de panneau du matériau sélectionné en stock",
    CONSIDER_MATERIALS: "Tenir compte du matériau",

    EDGE_BANDING: "Chants",
    EDGE_BAND: "Chant latéral",
    TOP_EDGE_BAND: "Chant en haut",
    LEFT_EDGE_BAND: "Chant à gauche",
    BOTTOM_EDGE_BAND: "Chant en bas",
    RIGHT_EDGE_BAND: "Chant à droite",
    CREATE_EDGE_BAND: "Nouveau type de chant",

    ORIENTATION_MATTERS: "Tenir compte de l'orientation du fil",
    NO_GRAIN: "Pas pris en compte",
    HORIZONTAL_GRAIN: "Fil suivant la largeur",
    VERTICAL_GRAIN: "Fil suivant la longueur",

    CALCULATIONS_PER_WEEK: "Calculs par semaine",
    UNLIMITED: "Illimité",
    FREE: "Gratuit",
    MONTHLY: "Mensuel",
    TERMS_OF_SERVICE: "Terms of service",
    PRIVACY_POLICY: "Privacy policy",
    CONTACT_EMAIL: "Contact Email:",

    SERVER_UNAVAILABLE: "Problème de serveur, veuillez réessayer plus tard",
    TASK_ALREADY_RUNNING: "Un seul calcul autorisé à la fois",
    TOO_MANY_PANELS: "Impossible de faire des calculs avec plus de 1000 panneaux",
    TOO_MANY_STOCK_PANELS: "Impossible de faire des calculs avec plus de 1000 panneaux en stock",
    LIMITS_REACHED: "Vous avez atteint votre limite hebdomadaire. Veuillez passer à la version pro",
    OPEN_RUNNING_CALC: "Ouvrir calcul en cours",

    ABOUT_MSG_1: "CutList Optimizer est une application destinée à l'optimisation de la découpe de panneaux. Il génère des schémas de découpe optimisés en fonction des feuilles disponibles en stock en imbriquant les pièces demandées au mieux",
    ABOUT_MSG_2: "Toutes les fonctionnalités sont entièrement disponibles gratuitement, dans la limite d'un certain nombre de calculs par semaine",
    ABOUT_MSG_3: "Si vous appréciez cette application, pensez à passer à la version Pro pour contribuer à son développement. Vous pouvez également mettre à niveau votre compte sur le site Web et  aurez accès à la version Android Pro et aux fonctionnalités premium du site Web",
    SUBSCRIPTION_MSG_1: "Contribuez à CutList Optimizer en souscrivant à la version pro",
    SUBSCRIPTION_ADDITINAL_MSG_1: "La souscription prend effet immédiatement",
    SUBSCRIPTION_ADDITINAL_MSG_2: "Votre compte Paypal sera débité automatiquement au début de chaque période d'abonnement",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Vous pourrez vous désinscrire à tout moment via votre compte Paypal",

    SUBSCRIPTION_INVOICE: "VAT Invoice can be requested through",

    TRY_WEB_MSG: "CutList Optimizer est également disponible sur le Web. La version Web offre des fonctionnalités optimisées et utilise un serveur dédié permettant des calculs plus rapides",

    SAVED_ITEM_LIMIT_REACHED: "Nombre maximum d'objets sauvegardés atteint",
    SUBSCRIPTION_ACTIVE: "Votre abonnement est activé",
    SUBSCRIPTION_PLAN: "Plan d'abonnement",
    CONTRIBUTE: "Contribuer",
    SUBSCRIBE: "Souscrire",
    ACTIVE: "Actif",
    PER_DAY: "par jour",
    CLIENT_STATS: "Statistiques",
    ALLOWED_CALCULATIONS: "Calculs autorisés",
    CALCULATION_SPEED: "Vitesse de calcul",
    SAVED_ITEMS: "Objets sauvegardés",
    PRICE: "Prix",
    GOLD: "Or",
    SILVER: "Argent",

    DIMENSIONS_TO_LABELS: "Inclure les dimensions sur l'étiquette",
    REPLACE_LABELS_QUESTION: "Remplacer étiquettes en cours ?",

    WHATS_NEW: "Quoi de neuf ?",

    FILENAME: "Nom",
    FONT_SIZE: "Taille de police",
    BIG: "Grande",
    HUGE: "Enorme",
    SEARCH: "Rechercher",
    RENAME: "Renommer",
    RENAMED: "Renommé",
    SAVE: "Sauvegarder",

    PDF_HEADER_TEXT: "Texte d'en tête",
    PDF_ADDITIONAL_TEXT: "Texte additionel",
    PDF_SHOW_SUMMARY: "Afficher résumé",
    PDF_SHOW_DATE: "Afficher la date",
    PDF_SHOW_CUTS_TABLE: "Montrer les tables de coupe",

    UNSAVED_CHANGES: "Les modifications non enregistrées seront perdues. Voulez-vous continuer ?",
    ALREADY_EXISTS: "existe déjà!",

    GENERIC_ERROR_MSG: "Une erreur est survenue !",

    PRO_FEATURE: "Fonctionnalité pro",
    PRO_FEATURES: "Fonctionnalités pro",

    CUT_ORIENTATION_PREFERENCE: "Orientation des coupes",
    CUT_ORIENTATION_PREFERENCE_NONE: "Optimal",
    CUT_ORIENTATION_PREFERENCE_WIDTH: "Coupes suivant la largeur",
    CUT_ORIENTATION_PREFERENCE_LENGTH: "Coupes suivant la longueur"
}
