// Italian
var translationsIT = {
    TITLE: "CutList Optimizer",
    PRO_VERSION: "Versione PRO",
    PANEL: "Pezzo",
    PANELS: "Pezzi",
    STOCK_PANEL: "Pannello",
    STOCK: "Pannelli",
    WIDTH: "Altezza",
    HEIGHT: "Lunghezza",
    QUANTITY: "Quantità",
    LABEL: "Descrizione",
    CUT: "Taglio",
    CUTS: "Tagli",
    TOTAL_CUTS_NBR: "Totale tagli",
    CUT_LENGTH: "Lunghezza taglio",
    TOTAL_CUT_LENGTH: "Lunghezza totale taglio",
    DIM: "Dimensione",
    USED_AREA: "Area utilizzata",
    TOTAL_USED_AREA: "Totale area utilizzata",
    WASTED_AREA: "Area avanzata",
    TOTAL_WASTED_AREA: "Totale area avanzata",
    WASTED_PANELS: "Materiale avanzato",
    STATS: "Statistiche generali",
    SHEET_STATISTICS: "Statistiche materiale",
    NBR_MOSAICS: "Pannelli utilizzati",
    UNABLE_TO_FIT: "Impossibile strutturare",
    CUT_THICKNESS: "Spessore lama/taglio",

    NAME: "Nome",
    NONE: "Nessuno",
    CALCULATE: "Calcola",
    ACCEPT: "Accetta",
    CANCEL: "Annulla",
    ERROR: "Errore",
    OPTIONS: "Opzioni",
    SETTINGS: "Impostazioni",
    LANGUAGE: "Lingua",
    ENABLE: "Abilita",
    DISABLE: "Disabilita",
    ENABLED: "Abilitato",
    DISABLED: "Disabilitato",
    REMOVE: "Rimuovi",
    REMOVED: "Rimosso",
    LOW: "Basso",
    NORMAL: "Normale",
    HIGH: "Alto",
    UPGRADE: "Promuovere",
    ABOUT: "Circa",
    DELETE: "Cancella",
    SAVED: "Salvato",
    DELETED: "Cancellato",
    LOADED: "Caricato",
    LOGOUT: "Esci",
    ADD_NEW: "Aggiungi nuovo",

    ADD_LINE: "Aggiungi nuova linea",
    LOAD: "Carica lista",
    SAVE_LIST: "Salva lista",
    ENABLE_DISABLE_ALL: "Abilita / Disabilita tutto",
    DELETE_ALL: "Cancella",
    EXPORT_CSV: "Esporta in formato CSV",
    IMPORT_CSV: "Esporta da formato CSV",
    CLEAR_LIST: "Cancellare la lista?",
    RESET_DATA: "Cancellare tutti i dati",

    EMAIL: "Email",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confermare Password",
    SIGN_IN: "Accedi",
    SIGN_OUT: "Esci",
    SIGN_UP: "Iscriviti",
    OR: "o",
    SIGN_IN_GOOGLE: "Iscriviti con Google",
    FORGOT_PASS: "Password dimenticata?",
    PASS_RESET: "Resetta la password",
    PASS_RESET_MSG: "Inserisci la tua Email. Riceverai un link per per creare una nuova password",
    PASS_SAVE_MSG: "Inserisci la nuova password",
    LOGIN_REQUEST: "Accedi per utilizzare questa funzionalità",

    PDF_PAGE: "Pagina",
    REPORT_AN_ISSUE: "Segnala un problema",
    OPTIMIZATION_PRIORITY: "Priorità di ottimizzazione",
    LEAST_WASTED_AREA: "Minima area sprecata",
    LEAST_NUMBER_OF_CUTS: "Minima numero di tagli",

    ZOOM_IN: "Ingrandire",
    ZOOM_OUT: "Ridurre",
    INCREASE_FONT_SIZE: "Aumenta la dimensione del carattere",
    DECREASE_FONT_SIZE: "Riduci le dimensioni del carattere",
    RESET_ZOOM: "Reimposta vista",
    ROTATE_90: "Ruota di 90º",
    PANEL_LABELS: "Descrizione dei pezzi",
    COLORED_PANELS: "Colora i pezzi",
    SHOW_CUTS: "Ordine dei tagli",
    SHOW_DIMENSIONS: "Dimensioni",

    SAVE_PROJECT: "Salva il progetto",
    LOAD_PROJECT: "Carica il progetto",
    NO_SAVED_DATA: "Dati non salvati",
    OVERWRITE: "Sovrascrivere",
    SAVE_AS: "Salva come",
    ALREADY_EXISTS: "Già esistente",

    INITIALIZING: "Inizializzazione",
    COMPUTING: "Calcolo",
    SEARCHING_BEST: "Ricerca della migliore soluzione",
    EXPORT_PDF: "Esporta in formato PDF",
    EXPORT_IMG: "Esporta in formato JPG",
    EXPORTING_PDF: "Creazione del PDF",
    EXPORTING_IMG: "Creazione dell’immagine",
    NOTHING_TO_EXPORT: "Niente da esportare",
    CLICK_TO_ACCEPT: "Clicca per accettare la soluzione",
    TAP_TO_ACCEPT: "Tocca per accettare la soluzione",
    MSG_NO_PANELS: "Nessun pezzo indicato",
    MSG_NO_STOCK_PANELS: "Nessun pannello indicato",
    // TODO: OPTIMIZATION_LEVEL: "Livello di ottimizzazione",
    IMAGE_PAN_ZOOM: "Abilita panoramica e zoom delle immagini",
    FORCE_ONE_STOCK_PANEL: "Utilizza solo un pannello",

    UNITS: "Unità di misura",
    DECIMAL_PLACES: "Decimali",
    GENERIC: "Generica (16.5)",
    MM: "Millimetri (16.5 mm)",
    CM: "Centimetri (16.5 cm)",
    INCHES: "Pollici (16.5\")",
    FEET_INCHES: "Piedi e pollici decimali (1' 4.5\")",
    FEET_INCHES_FRAC: "Piedi e pollici frazionati (1' 4 1/2\")",
    INCHES_FRAC: "Pollici frazionari (16 1/2\")",

    MATERIAL: "Materiale",
    CREATE_MATERIAL: "Crea un nuovo tipo di materiale",
    MSG_NO_STOCK_MATERIAL: "Nessun pannello disponibile del materiale richiesto",
    CONSIDER_MATERIALS: "Considerare il materiale",

    EDGE_BANDING: "Bordatura",
    EDGE_BAND: "Bordo",
    TOP_EDGE_BAND: "Bordo superiore",
    LEFT_EDGE_BAND: "Bordo sinistro",
    BOTTOM_EDGE_BAND: "Bordo inferiore",
    RIGHT_EDGE_BAND: "Bordo destro",
    CREATE_EDGE_BAND: "Crea un nuovo tipo di bordo",

    ORIENTATION_MATTERS: "Considera la direzione della venatura",
    NO_GRAIN: "Non considerare la direzione della venatura",
    HORIZONTAL_GRAIN: "Venatura orizzontale",
    VERTICAL_GRAIN: "Venatura verticale",

    CALCULATIONS_PER_WEEK: "Calcoli a settimana",
    UNLIMITED: "illimitato",
    FREE: "Gratuito",
    MONTHLY: "mensile",
    TERMS_OF_SERVICE: "Termini di servizio",
    PRIVACY_POLICY: "Politica sulla riservatezza",
    CONTACT_EMAIL: "Contatto email:",

    SERVER_UNAVAILABLE: "Server momentaneamente non disponbile, riprova più tardi",
    TASK_ALREADY_RUNNING: "È consentito una sola elaborazione alla volta",
    TOO_MANY_PANELS: "Impossibile eseguire il calcolo con più di 1000 pannelli",
    TOO_MANY_STOCK_PANELS: "Impossibile eseguire il calcolo con più di 1000 fogli di scorta",
    LIMITS_REACHED: "È stato raggiunto il limite di calcolo giornaliero gratuito. Si prega di considerare di supportare lo sviluppo.",
    OPEN_RUNNING_CALC: "Apri calcolo in esecuzione",

    ABOUT_MSG_1: "CutList Optimizer è un'applicazione per ottimizzare il processo di taglio di materiale",
    ABOUT_MSG_2: "Genera layout di taglio ottimizzati in base ai pannelli disponibili combinando il numero di pezzi richiesti.",
    ABOUT_MSG_3: "Se trovi utile questa app, considera l'aggiornamento alla versione Pro per supportarne lo sviluppo. In alternativa, puoi aggiornare il tuo account all'interno del sito Web e avrai accesso sia alla versione Android Pro sia alle funzionalità premium del sito Web.",
    SUBSCRIPTION_MSG_1: "Contribuisci a CutList Optimizer aggiornando alla versione Pro.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "L'iscrizione avrà effetto immediato",
    SUBSCRIPTION_ADDITINAL_MSG_2: "Il tuo conto PayPal verrà addebitato automaticamente all'inizio di ogni ciclo di fatturazione",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "Il primo ciclo di fatturazione mensile inizia il giorno in cui si attiva il servizio",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "Non sono previsti rimborsi o crediti per mesi parziali",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Puoi annullare l'abbonamento in qualsiasi momento sul tuo conto PayPal e puoi continuare a utilizzare il servizio fino al termine del periodo di fatturazione",

    TRY_WEB_MSG: "CutList Optimizer è disponibile anche sul Web. La versione Web offre funzionalità ottimizzate e utilizza un server dedicato che fornisce calcoli più rapidi: "
};
