// Hebrew
var translationsHE = {
    TITLE: "CutList Optimizer",
    PRO_VERSION: "גרסת מקצוען",
    PANEL: "פנל",
    PANELS: "(לוחות לחיתוך (פנלים\\צדדים",
    STOCK_PANEL: "גודל הפלטה",
    STOCK: "לוחות\\פלטות במאגר\\מחסן\\לחישוב",
    WIDTH: "רוחב",
    HEIGHT: "אורך",
    QUANTITY: "כמות",
    LABEL: "תווית \\ שם",
    CUT: "חיתוך",
    CUTS: "חיתוכים",
    TOTAL_CUTS_NBR: "סך הכל חיתוכים",
    CUT_LENGTH: "חיתוכים באורך",
    TOTAL_CUT_LENGTH: "סך הכל חיתוכים באורך",
    DIM: "מֵמַד",
    USED_AREA: "שטח בשימוש",
    TOTAL_USED_AREA: "סך הכל שטח בשימוש",
    WASTED_AREA: "שטח לא מנוצל",
    TOTAL_WASTED_AREA: "(סך הכל שטח לא מנוצל (מבוזבז",
    WASTED_PANELS: "פנלים לא מנוצלים",
    STATS: "סטטיסטיקה גלובלית",
    SHEET_STATISTICS: "סטטיסטיקה פר פלטה",
    NBR_MOSAICS: "מספר פלטות בשימוש",
    UNABLE_TO_FIT: "לא ניתן להכניס",
    CUT_THICKNESS: "גודל להב החיתוך",

    NAME: "שם",
    NONE: "אף אחד",
    CALCULATE: "חשב",
    ACCEPT: "מאשר",
    CANCEL: "בטל",
    ERROR: "שגיאה",
    OPTIONS: "אופציות",
    SETTINGS: "הגדרות",
    LANGUAGE: "שפה",
    ENABLE: "אפשר",
    DISABLE: "להשבית (לא לאפשר)",
    ENABLED: "מופעל",
    DISABLED: "נכים",
    REMOVE: "הסר",
    REMOVED: "הוסר",
    LOW: "נמוכה",
    NORMAL: "רגיל",
    HIGH: "גבוה",
    UPGRADE: "שדרג",
    ABOUT: "על אודות",
    DELETE: "מחק",
    SAVED: "שמור",
    DELETED: "נמחק",
    LOADED: "עמוס",
    LOGOUT: "להתנתק",
    ADD_NEW: "הוסף חדש",

    ADD_LINE: "הוסף שורה חדשה",
    LOAD: "טען רשימה שמורה",
    SAVE_LIST: "שמור רשימה",
    ENABLE_DISABLE_ALL: "הפעל / השבת את הכל",
    DELETE_ALL: "מחק הכל",
    EXPORT_CSV: "ייצא ל- CSV",
    IMPORT_CSV: "ייבא מ- CSV",
    CLEAR_LIST: "נקה רשימה?",
    RESET_DATA: "פרויקט ריק חדש",

    EMAIL: "אימייל",
    PASSWORD: "סיסמה",
    CONFIRM_PASSWORD: "אשר סיסמה",
    SIGN_IN: "להתחבר",
    SIGN_OUT: "התנתק",
    SIGN_UP: "הירשם",
    OR: "או",
    SIGN_IN_GOOGLE: "היכנס באמצעות Google",
    FORGOT_PASS: "שכחת ססמה?",
    PASS_RESET: "איפוס סיסמא",
    PASS_RESET_MSG: "אנא הכנס את הדוא\"ל שלך. תקבל קישור ליצירת סיסמה חדשה.",
    PASS_SAVE_MSG: "אנא הכנס את הסיסמה החדשה שלך.",
    LOGIN_REQUEST: "אנא היכנס תחילה",

    PDF_PAGE: "עמוד",
    REPORT_AN_ISSUE: "דווח על בעיה",
    OPTIMIZATION_PRIORITY: "עדיפות אופטימיזציה",
    LEAST_WASTED_AREA: "פחות שטח מבוזבז",
    LEAST_NUMBER_OF_CUTS: "פחות חיתוכים",

    ZOOM_IN: "התקרב",
    ZOOM_OUT: "להקטין את התצוגה",
    INCREASE_FONT_SIZE: "הגדל את גודל הגופן",
    DECREASE_FONT_SIZE: "צמצם את גודל הגופן",
    RESET_ZOOM: "לאפס תצוגה",
    ROTATE_90: "סובב 90 מעלות",
    PANEL_LABELS: "אפשר תווית\\שם על פנלים\\חיתוכים",
    COLORED_PANELS: "צבע ביצוא הקובץ",
    SHOW_CUTS: "(סדר חיתוכים (ממוספר מ1 ומעלה",
    SHOW_DIMENSIONS: "ממדים",

    SAVE_PROJECT: "שמור פרוייקט",
    LOAD_PROJECT: "טען פרויקט",
    NO_SAVED_DATA: "אין נתונים שנשמרו",
    OVERWRITE: "להחליף",
    SAVE_AS: "שמירה בשם",
    ALREADY_EXISTS: "כבר קיים",

    INITIALIZING: "אתחול",
    COMPUTING: "מחשב...",
    SEARCHING_BEST: "מחפש את הפיתרון הטוב ביותר",
    EXPORT_PDF: "יצא לקובץ PDF",
    EXPORT_IMG: "יצא כתמונה",
    EXPORTING_PDF: "מיצא לקובץ PDF...",
    EXPORTING_IMG: "מיצא לתמונה...",
    NOTHING_TO_EXPORT: "אין מה לייצא",
    CLICK_TO_ACCEPT: "לחץ לאפשר",
    TAP_TO_ACCEPT: "לחץ לאפשר.",
    MSG_NO_PANELS: "לא נבחר פנל",
    MSG_NO_STOCK_PANELS: "לא נבחר פלטה",
    // TODO: OPTIMIZATION_LEVEL: "רמת אופטימיזציה",
    IMAGE_PAN_ZOOM: "אפשר זום (הקרבה והרחקה) של התמונה",
    FORCE_ONE_STOCK_PANEL: "השתמש רק בפלטה אחת בלבד מן המחסן",

    UNITS: "יחידות",
    DECIMAL_PLACES: "מקומות עשרוניים",
    GENERIC: "(16.5) גנרי",
    MM: "(16.5 mm) מילימטרים",
    CM: "(16.5 cm) סנטימטרים",
    INCHES: "(16.5\") סנטימטרים",
    FEET_INCHES: "(1' 4.5\") רגליים ועשרון עשרוני",
    FEET_INCHES_FRAC: "(1' 4 1/2\") רגליים חלקיות ואינץ",
    INCHES_FRAC: "(16 1/2\") חלקי סנטימטרים",

    MATERIAL: "חומר",
    CREATE_MATERIAL: "צור סוג חומר חדש",
    MSG_NO_STOCK_MATERIAL: "אין גיליון מלאי זמין של חומר נדרש",
    CONSIDER_MATERIALS: "שקול חומר",

    EDGE_BANDING: "פסי קצה",
    EDGE_BAND: "להקת קצה",
    TOP_EDGE_BAND: "רצועת הקצה העליונה",
    LEFT_EDGE_BAND: "רצועת הקצה השמאלי",
    BOTTOM_EDGE_BAND: "רצועת הקצה התחתון",
    RIGHT_EDGE_BAND: "רצועת הקצה הימני",
    CREATE_EDGE_BAND: "צור סוג פס חדש",

    ORIENTATION_MATTERS: "שקול כיוון התבואה",
    NO_GRAIN: "אין התחשבות בדגן",
    HORIZONTAL_GRAIN: "גרגרים לאורך רוחב",
    VERTICAL_GRAIN: "גרגרים לאורך",

    CALCULATIONS_PER_WEEK: "חישובים לשבוע",
    UNLIMITED: "ללא הגבלה",
    FREE: "חינם",
    MONTHLY: "חודשי",
    TERMS_OF_SERVICE: "תנאי השירות",
    PRIVACY_POLICY: "מדיניות הפרטיות",
    CONTACT_EMAIL: "דוא\ל ליצירת קשר:",

    SERVER_UNAVAILABLE: "השרת נתקל בבעיות מסוימות, נסה שוב מאוחר יותר.",
    TASK_ALREADY_RUNNING: "רק חישוב אחד מותר לפעול בבת אחת",
    TOO_MANY_PANELS: "לא ניתן לבצע חישובים עם יותר מ- 1000 פאנלים",
    TOO_MANY_STOCK_PANELS: "לא ניתן לבצע חישובים עם יותר מ- 1000 גיליונות מלאי",
    LIMITS_REACHED: "הושגה מגבלת החישוב היומית בחינם. אנא שקול לתמוך בפיתוח.",
    OPEN_RUNNING_CALC: "חישוב ריצה פתוח",

    ABOUT_MSG_1: "כלי אופטימיזציית CutList הוא יישום המיועד לאופטימיזציה של חיתוך פאנלים. זה מייצר דפוסי חיתוך אופטימליים על בסיס גיליונות המלאי הזמינים על ידי קינון החלקים הנדרשים.",
    ABOUT_MSG_2: "כל התכונות זמינות במלואן בחינם בתוך מספר מצומצם של חישובים בשבוע.",
    ABOUT_MSG_3: "אם אתה מוצא יישום זה שימושי, אנא שקול לשדרג לגרסת ה- Pro כדי לתמוך בפיתוח שלה. לחלופין, תוכל לשדרג את חשבונך באתר האינטרנט ויהיה לך גישה גם לגרסת ה- Android Pro וגם לתכונות הפרימיום של האתר.",
    SUBSCRIPTION_MSG_1: "תרמו לכלי האופטימיזציה של CutList על ידי שדרוג לגרסת ה- Pro.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "המינוי ייכנס לתוקף באופן מיידי",
    SUBSCRIPTION_ADDITINAL_MSG_2: "חשבון PayPal שלך יחויב אוטומטית בתחילת כל מחזור חיוב",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "מחזור החיוב החודשי הראשון מתחיל ביום הפעלת השירות",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "אין החזרים או נקודות זיכוי במשך חודשים חלקיים",
    SUBSCRIPTION_ADDITINAL_MSG_5: "אתה רשאי לבטל את המנוי שלך בכל עת בחשבון PayPal שלך ותוכל להמשיך להשתמש בשירות עד שתקופת החיוב שלך תסתיים",

    TRY_WEB_MSG: "כלי האופטימיזציה של CutList זמין גם באינטרנט. גרסת האינטרנט מספקת תכונות מותאמות ועושה שימוש בשרת ייעודי המספק חישובים מהירים יותר:"
};
