// Persian
var translationsFA= {
    TITLE: "بهینه ساز لیست برش",
    PRO_VERSION: "نسخه حرفه ای",
    PANEL: "صفحه",
    PANELS: "صفحه ها",
    STOCK_PANEL: "ورق سهام",
    STOCK: "موجودی",
    WIDTH: "عرض",
    HEIGHT: "طول",
    QUANTITY: "تعداد",
    LABEL: "برچسب",
    CUT: "برش",
    CUTS: "برش ها",
    TOTAL_CUTS_NBR: "کل کاهش",
    CUT_LENGTH: "طول برش",
    TOTAL_CUT_LENGTH: "طول کل برش",
    DIM: "اندازه",
    USED_AREA: "مساحت استفاده شده",
    TOTAL_USED_AREA: "منطقه مورد استفاده در کل",
    WASTED_AREA: "مساحت تلف شده",
    TOTAL_WASTED_AREA: "کل منطقه مسموم شده است",
    WASTED_PANELS: "صفحه های هدر رفته",
    STATS: "آمار جهانی",
    SHEET_STATISTICS: "آمار ورق",
    NBR_MOSAICS: "ورق های مورد استفاده",
    UNABLE_TO_FIT: "ناتوان در تناسب",
    CUT_THICKNESS: "ضخامت برش",

    NAME: "نام",
    NONE: "هیچ یک",
    CALCULATE: "محاسبه کردن",
    ACCEPT: "پذیرفتن",
    CANCEL: "لغو",
    ERROR: "اخطار",
    OPTIONS: "گزینه ها",
    SETTINGS: "تنظیمات",
    LANGUAGE: "زبان",
    ENABLE: "فعال کردن",
    DISABLE: "غیرفعال کردن",
    ENABLED: "فعال شده است",
    DISABLED: "معلول",
    REMOVE: "برداشتن",
    REMOVED: "حذف شده",
    LOW: "کم",
    NORMAL: "طبیعی",
    HIGH: "بالا",
    UPGRADE: "ارتقا",
    ABOUT: "در باره",
    DELETE: "حذف",
    SAVED: "ذخیره",
    DELETED: "حذف شده",
    LOADED: "لود شده",
    LOGOUT: "خروج",
    ADD_NEW: "جدید اضافه کن",

    ADD_LINE: "خط اضافه کنید",
    LOAD: "بار",
    SAVE_LIST: "صرفه جویی",
    ENABLE_DISABLE_ALL: "فعال یا غیرفعال کردن همه",
    DELETE_ALL: "حذف همه",
    EXPORT_CSV: "صادرات به CSV",
    IMPORT_CSV: "واردات از CSV",
    CLEAR_LIST: "لیست پاک کنید؟",
    RESET_DATA: "پروژه جدید خالی",

    EMAIL: "پست الکترونیک",
    PASSWORD: "کلمه عبور",
    CONFIRM_PASSWORD: "رمز عبور را تأیید کنید",
    SIGN_IN: "ورود",
    SIGN_OUT: "خروج از سیستم",
    SIGN_UP: "ثبت نام",
    OR: "یا",
    SIGN_IN_GOOGLE: "با Google وارد سیستم شوید",
    FORGOT_PASS: "رمز ورود خود را فراموش کرده اید؟",
    PASS_RESET: "تنظیم مجدد رمز عبور",
    PASS_RESET_MSG: "لطفا ایمیل خود را وارد کن. برای ایجاد گذرواژه جدید پیوند دریافت خواهید کرد.",
    PASS_SAVE_MSG: "لطفاً رمز جدید خود را وارد کنید",
    LOGIN_REQUEST: "لطفا ابتدا وارد سیستم شوید",

    PDF_PAGE: "صفحه",
    REPORT_AN_ISSUE: "گزارش یک مسئله",
    OPTIMIZATION_PRIORITY: "اولویت بهینه سازی",
    LEAST_WASTED_AREA: "منطقه کمترین هدر رفته",
    LEAST_NUMBER_OF_CUTS: "حداقل تعداد کاهش",

    ZOOM_IN: "بزرگنمایی",
    ZOOM_OUT: "کوچک نمایی",
    INCREASE_FONT_SIZE: "اندازه قلم را افزایش دهید",
    DECREASE_FONT_SIZE: "اندازه قلم را کاهش دهید",
    RESET_ZOOM: "نمایش تنظیم مجدد",
    ROTATE_90: "چرخش 90º",
    PANEL_LABELS: "برچسب ها در پانل ها",
    COLORED_PANELS: "پانل های پر رنگ",
    SHOW_CUTS: "سفارش کاهش",
    SHOW_DIMENSIONS: "ابعاد",

    SAVE_PROJECT: "ذخیره پروژه",
    LOAD_PROJECT: "بارگذاری پروژه",
    NO_SAVED_DATA: "داده ذخیره نشده است",
    OVERWRITE: "زیاد نوشتن",
    SAVE_AS: "ذخیره به عنوان",
    ALREADY_EXISTS: "همین الان هم وجود داره",

    INITIALIZING: "مقدماتی",
    COMPUTING: "محاسبه",
    SEARCHING_BEST: "در جستجوی بهترین راه حل",
    EXPORT_PDF: "Pdf ارسال به",
    EXPORT_IMG: "صادرات به تصویر",
    EXPORTING_PDF: "تولید PDF",
    EXPORTING_IMG: "ایجاد تصویر",
    NOTHING_TO_EXPORT: "هیچ چیز برای صادرات نیست",
    CLICK_TO_ACCEPT: "برای پذیرش راه حل کلیک کنید",
    TAP_TO_ACCEPT: "برای پذیرش راه حل ، ضربه بزنید",
    MSG_NO_PANELS: "هیچ صفحه ای تعیین نشده",
    MSG_NO_STOCK_PANELS: "هیچ صفحه از موجودی تعیین نشده",
    // TODO: OPTIMIZATION_LEVEL: "سطح بهینه سازی",
    IMAGE_PAN_ZOOM: "فعال کردن قاب تصویر و بزرگنمایی",
    FORCE_ONE_STOCK_PANEL: "تنها یک صفحه از موجودی استفاده بشود",

    UNITS: "واحدها",
    DECIMAL_PLACES: "مکان های اعشار",
    GENERIC: "(16.5) عمومی",
    MM: "(16.5 mm) میلی متر",
    CM: "(16.5 cm) سانتیمتر",
    INCHES: "(16.5\") اینچ",
    FEET_INCHES: "(1' 4.5\") پای دهانه و اینچ",
    FEET_INCHES_FRAC: "(1' 4 1/2\") پا و اینچ کسری",
    INCHES_FRAC: "(16 1/2\") اینچ کسری",

    MATERIAL: "مواد",
    CREATE_MATERIAL: "نوع جدیدی از مواد ایجاد کنید",
    MSG_NO_STOCK_MATERIAL: "هیچ برگه سهام موجودی از مواد مورد نیاز موجود نیست",
    CONSIDER_MATERIALS: "مواد را در نظر بگیرید",

    EDGE_BANDING: "بانداژ",
    EDGE_BAND: "باند لبه",
    TOP_EDGE_BAND: "باند بالا",
    LEFT_EDGE_BAND: "باند لبه سمت چپ",
    BOTTOM_EDGE_BAND: "باند پایین لبه",
    RIGHT_EDGE_BAND: "باند لبه راست",
    CREATE_EDGE_BAND: "نوع باند جدیدی ایجاد کنید",

    ORIENTATION_MATTERS: "جهت دانه را در نظر بگیرید",
    NO_GRAIN: "بدون توجه به دانه",
    HORIZONTAL_GRAIN: "دانه به طول عرض",
    VERTICAL_GRAIN: "طول طول دانه",

    CALCULATIONS_PER_WEEK: "محاسبات در هفته",
    UNLIMITED: "نامحدود",
    FREE: "رایگان",
    MONTHLY: "ماهانه",
    TERMS_OF_SERVICE: "شرایط استفاده از خدمات",
    PRIVACY_POLICY: "سیاست حفظ حریم خصوصی",
    CONTACT_EMAIL: "تماس با ایمیل:",

    SERVER_UNAVAILABLE: "سرور در حال حاضر مشکلی را تجربه می کند ، لطفا بعداً دوباره امتحان کنید.",
    TASK_ALREADY_RUNNING: "فقط یک محاسبه مجاز به اجرای همزمان است",
    TOO_MANY_PANELS: "محاسبه با بیش از 1000 پانل امکان پذیر نیست",
    TOO_MANY_STOCK_PANELS: "انجام بیش از 1000 برگه سهام امکان انجام محاسبه وجود ندارد",
    LIMITS_REACHED: "حد محاسبه روزانه رایگان شما رسیده است لطفا حمایت از توسعه را در نظر بگیرید.",
    OPEN_RUNNING_CALC: "محاسبه در حال اجرا باز کنید",

    ABOUT_MSG_1: "CutList Optimizer برنامه ای است که برای بهینه سازی برش پانل در نظر گرفته شده است. با ایجاد لانه کردن قطعات مورد نیاز ، الگوهای برش بهینه را بر اساس برگه سهام موجود ایجاد می کند.",
    ABOUT_MSG_2: "همه ویژگی ها به طور رایگان و در تعداد محدودی از محاسبات در هفته به طور رایگان در دسترس هستند.",
    ABOUT_MSG_3: "اگر این برنامه را مفید می دانید ، لطفاً برای پشتیبانی از توسعه آن ، به نسخه Pro ارتقا دهید. از طرف دیگر ، می توانید حساب خود را در وب سایت ارتقا دهید و به نسخه Android Pro و ویژگی های حق بیمه وب سایت دسترسی خواهید داشت.",
    SUBSCRIPTION_MSG_1: "با بروزرسانی به نسخه Pro ، به CutList Optimizer کمک کنید.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "اشتراک بلافاصله اجرا می شود",
    SUBSCRIPTION_ADDITINAL_MSG_2: "در ابتدای هر چرخه صورتحساب ، حساب پی پال شما به طور خودکار شارژ می شود",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "اولین چرخه صورتحساب ماهانه از روزی که سرویس را فعال می کنید شروع می شود",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "هیچ بازپرداخت یا اعتبار برای ماههای جزئی وجود ندارد",
    SUBSCRIPTION_ADDITINAL_MSG_5: "شما می توانید اشتراک خود را در هر زمان و در حساب پی پال خود لغو کنید و ممکن است تا پایان دوره صورتحساب خود استفاده از این سرویس را ادامه دهید",

    TRY_WEB_MSG: "CutList Optimizer نیز در وب موجود است. نسخه وب ویژگی های بهینه سازی شده را ارائه می دهد و از سرور اختصاصی محاسبات سریعتر استفاده می کند:"
};
