// German
var translationsDE = {

    TITLE: "CutList Optimizer",
    PRO_VERSION: "Pro version",
    PANEL: "Kachel",
    PANELS: "Kacheln",
    STOCK_PANEL: "Bestandsblatt",
    STOCK: "Bestand",
    WIDTH: "Breite",
    HEIGHT: "Länge",
    QUANTITY: "Stückzahl",
    LABEL: "Etikette",
    CUT: "Schnitt",
    CUTS: "Schnitte",
    TOTAL_CUTS_NBR: "Totale Schnitte",
    CUT_LENGTH: "Schnittlänge",
    TOTAL_CUT_LENGTH: "Gesamtschnittlänge",
    DIM: "Maß",
    USED_AREA: "Genutzte Fläche",
    TOTAL_USED_AREA: "Gesamtnutzfläche",
    WASTED_AREA: "Verschwendete Fläche",
    TOTAL_WASTED_AREA: "Gesamtabfallfläche",
    WASTED_PANELS: "Verschwendete Kacheln",
    STATS: "Globale Statistiken",
    SHEET_STATISTICS: "Blattstatistiken",
    NBR_MOSAICS: "Verwendete Bestandsblätter",
    UNABLE_TO_FIT: "Kann nicht passen",
    CUT_THICKNESS: "Schnittbreite",

    NAME: "Name",
    NONE: "Keiner",
    CALCULATE: "Berechnen",
    ACCEPT: "Akzeptieren",
    CANCEL: "Abbrechen",
    ERROR: "Fehler",
    OPTIONS: "Optionen",
    SETTINGS: "Einstellungen",
    LANGUAGE: "Sprache",
    ENABLE: "Enable",
    DISABLE: "Disable",
    ENABLED: "Aktiviert",
    DISABLED: "Deaktiviert",
    REMOVE: "Entfernen",
    REMOVED: "Entfernt",
    LOW: "Niedrig",
    NORMAL: "Normal",
    HIGH: "Hoch",
    UPGRADE: "Aktualisierung",
    ABOUT: "Über",
    DELETE: "Löschen",
    SAVED: "Gerettet",
    DELETED: "Gelöscht",
    LOADED: "Geladen",
    LOGOUT: "Ausloggen",
    ADD_NEW: "Neue hinzufügen",

    ADD_LINE: "Zeile hinzufügen",
    LOAD: "Laden",
    SAVE_LIST: "Speichern",
    ENABLE_DISABLE_ALL: "Alle aktivieren / deaktivieren",
    DELETE_ALL: "Alle löschen",
    EXPORT_CSV: "In CSV exportieren",
    IMPORT_CSV: "Aus CSV importieren",
    CLEAR_LIST: "Liste leeren?",
    RESET_DATA: "Neues leeres Projekt",

    EMAIL: "Email",
    PASSWORD: "Passwort",
    CONFIRM_PASSWORD: "Passwort bestätigung",
    SIGN_IN: "Einloggen",
    SIGN_OUT: "Ausloggen",
    SIGN_UP: "Anmelden",
    OR: "oder",
    SIGN_IN_GOOGLE: "Anmeldung mit Google",
    FORGOT_PASS: "Passwort vergessen?",
    PASS_RESET: "Passwort zurücksetzen",
    PASS_RESET_MSG: "Bitte geben Sie ihre E-Mail-Adresse ein. Sie erhalten einen Link zum Erstellen eines neuen Passworts.",
    PASS_SAVE_MSG: "Bitte geben Sie Ihr neues Passwort ein.",
    LOGIN_REQUEST: "Bitte melden Sie sich zuerst an",

    PDF_PAGE: "page",
    REPORT_AN_ISSUE: "Ein Problem melden",
    OPTIMIZATION_PRIORITY: "Optimierungspriorität",
    LEAST_WASTED_AREA: "Am wenigsten verschwendeter Bereich",
    LEAST_NUMBER_OF_CUTS: "Mindestanzahl an Schnitten",

    ZOOM_IN: "Hineinzoomen",
    ZOOM_OUT: "Rauszoomen",
    INCREASE_FONT_SIZE: "Schriftgröße vergrößern",
    DECREASE_FONT_SIZE: "Schrift verkleinern",
    RESET_ZOOM: "Ansicht zurücksetzen",
    ROTATE_90: "Drehen 90º",
    PANEL_LABELS: "Etiketten auf den Paneelen",
    COLORED_PANELS: "Color filled panels",
    SHOW_CUTS: "Reihenfolge der Schnitte",
    SHOW_DIMENSIONS: "Maße",

    SAVE_PROJECT: "Projekt speichern",
    LOAD_PROJECT: "Projekt laden",
    NO_SAVED_DATA: "Keine gespeicherten Daten",
    OVERWRITE: "Überschreiben",
    SAVE_AS: "Speichern als",
    ALREADY_EXISTS: "Ist bereits vorhanden",

    INITIALIZING: "Initialisierung",
    COMPUTING: "Computing...",
    SEARCHING_BEST: "Auf der Suche nach der besten Lösung",
    EXPORT_PDF: "Als PDF exportieren",
    EXPORT_IMG: "Bild exportieren",
    EXPORTING_PDF: "Exporting to PDF...",
    EXPORTING_IMG: "Exporting to image...",
    NOTHING_TO_EXPORT: "Nichts zu exportieren",
    CLICK_TO_ACCEPT: "Klicken Sie, um die Lösung zu akzeptieren",
    TAP_TO_ACCEPT: "Tippen Sie auf, um die Lösung zu akzeptieren",
    MSG_NO_PANELS: "Keine Kacheln angegeben",
    MSG_NO_STOCK_PANELS: "Keine Betandskacheln angegeben",
    // TODO: OPTIMIZATION_LEVEL: "Optimierungsstufe",
    IMAGE_PAN_ZOOM: "Aktivieren Sie Bildschwenken und Zoomen",
    FORCE_ONE_STOCK_PANEL: "Nur eine Kachel aus dem Bestand nutzen",

    UNITS: "Einheiten",
    DECIMAL_PLACES: "Nachkommastellen",
    GENERIC: "Generisch (16.5)",
    MM: "Millimeter (16,5 mm)",
    CM: "Zentimeter (16,5 cm)",
    INCHES: "Zoll (16,5\")",
    FEET_INCHES: "Dezimalfuß & Zoll (1 '4.5 \")",
    FEET_INCHES_FRAC: "Bruchteil Füße & Zoll (1 '4 1/2\")",
    INCHES_FRAC: "Bruchzoll (16 1/2\")",

    MATERIAL: "Material",
    CREATE_MATERIAL: "Legen Sie einen neuen Materialtyp an",
    MSG_NO_STOCK_MATERIAL: "Kein verfügbares Lagerblatt des erforderlichen Materials",
    CONSIDER_MATERIALS: "Betrachten Sie Material",

    EDGE_BANDING: "Kantenanleimung",
    EDGE_BAND: "Kantenband",
    TOP_EDGE_BAND: "Oberes Randband",
    LEFT_EDGE_BAND: "Linkes Randband",
    BOTTOM_EDGE_BAND: "Unterkantenband",
    RIGHT_EDGE_BAND: "Rechtes Randband",
    CREATE_EDGE_BAND: "Neuen Kantenbandtyp erstellen",

    ORIENTATION_MATTERS: "Kornrichtung berücksichtigen",
    NO_GRAIN: "Keine Kornbetrachtung",
    HORIZONTAL_GRAIN: "Korn entlang der Breite",
    VERTICAL_GRAIN: "Korn entlang der Länge",

    CALCULATIONS_PER_WEEK: "Berechnungen pro Woche",
    UNLIMITED: "unbegrenzt",
    FREE: "Kostenlos",
    MONTHLY: "monatlich",
    TERMS_OF_SERVICE: "Nutzungsbedingungen",
    PRIVACY_POLICY: "Datenschutz-Bestimmungen",
    CONTACT_EMAIL: "Kontakt E-mail:",

    SERVER_UNAVAILABLE: "Auf dem Server treten derzeit einige Probleme auf. Versuchen Sie es später erneut.",
    TASK_ALREADY_RUNNING: "Es darf immer nur eine Berechnung gleichzeitig ausgeführt werden",
    TOO_MANY_PANELS: "Berechnung mit mehr als 1000 Anzeigen nicht möglich",
    TOO_MANY_STOCK_PANELS: "Berechnung mit mehr als 1000 Materialbögen nicht möglich",
    LIMITS_REACHED: "Ihr kostenloses tägliches Berechnungslimit wurde erreicht. Bitte unterstützen Sie die Entwicklung.",
    OPEN_RUNNING_CALC: "Laufende Berechnung öffnen",

    ABOUT_MSG_1: "CutList Optimizer ist eine Anwendung zur Optimierung des Plattenschnitts. Es generiert optimierte Schnittmuster basierend auf den verfügbaren Materialbögen, indem die erforderlichen Teile verschachtelt werden.",
    ABOUT_MSG_2: "Alle Funktionen sind innerhalb einer begrenzten Anzahl von Berechnungen pro Woche kostenlos verfügbar.",
    ABOUT_MSG_3: "Wenn Sie diese App nützlich finden, sollten Sie ein Upgrade auf die Pro-Version in Betracht ziehen, um deren Entwicklung zu unterstützen. Alternativ können Sie Ihr Konto innerhalb der Website aktualisieren und haben Zugriff auf die Android Pro-Version und die Premium-Funktionen der Website.",
    SUBSCRIPTION_MSG_1: "Tragen Sie zum CutList Optimizer bei, indem Sie auf die Pro-Version aktualisieren.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "Das Abonnement wird sofort wirksam",
    SUBSCRIPTION_ADDITINAL_MSG_2: "Ihr PayPal-Konto wird zu Beginn jedes Rechnungszyklus automatisch belastet",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "Der erste monatliche Abrechnungszyklus beginnt an dem Tag, an dem Sie den Service aktivieren",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "Für Teilmonate gibt es keine Rückerstattung oder Gutschrift",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Sie können Ihr Abonnement jederzeit über Ihr PayPal-Konto kündigen und den Service bis zum Ende Ihres Abrechnungszeitraums weiterhin nutzen",

    TRY_WEB_MSG: "CutList Optimizer ist auch im Web verfügbar. Die Webversion bietet optimierte Funktionen und verwendet einen dedizierten Server, der schnellere Berechnungen ermöglicht: "
};
