// Croatian
var translationsHR = {

    TITLE: "CutList Optimizer",
    PRO_VERSION: "Pro verzija",
    PANEL: "Ploča",
    PANELS: "Ploče",
    STOCK_PANEL: "Zalihe",
    STOCK: "Zalihe",
    WIDTH: "Širina",
    HEIGHT: "Dužina",
    QUANTITY: "kom",
    LABEL: "Oznaka",
    CUT: "Rez",
    CUTS: "Rezovi",
    TOTAL_CUTS_NBR: "Ukupno rezova",
    CUT_LENGTH: "Dužina reza",
    TOTAL_CUT_LENGTH: "Ukupna dužina rezova",
    DIM: "Dim",
    USED_AREA: "Iskorištena površina",
    TOTAL_USED_AREA: "Ukupna iskorištena površina",
    WASTED_AREA: "Otpad",
    TOTAL_WASTED_AREA: "Ukupan otpad",
    WASTED_PANELS: "Otpadne ploče",
    STATS: "Globalna statistika",
    SHEET_STATISTICS: "Statistika ploča",
    NBR_MOSAICS: "Iskorištene zalihe ploča",
    UNABLE_TO_FIT: "Ne može stati",
    CUT_THICKNESS: "Debljina reza / oštrice / zasjeka",

    NAME: "Ime",
    NONE: "Nema",
    CALCULATE: "Izračunaj",
    ACCEPT: "Prihvati",
    CANCEL: "Otkaži",
    ERROR: "Greška",
    OPTIONS: "Opcije",
    SETTINGS: "Postavke",
    LANGUAGE: "Jezik",
    ENABLE: "Omogući",
    DISABLE: "Onemogući",
    ENABLED: "Omogućeno",
    DISABLED: "Onemogućeno",
    REMOVE: "Ukloni",
    REMOVED: "Uklonjeno",
    LOW: "Nisko",
    NORMAL: "Normalno",
    HIGH: "Visoko",
    UPGRADE: "Nadogradnja",
    ABOUT: "O proizvodu",
    DELETE: "Ukloni",
    SAVED: "Spremljeno",
    DELETED: "Uklonjeno",
    LOADED: "Učitano",
    LOGOUT: "Odjava",
    ADD_NEW: "Dodaj novo",

    ADD_LINE: "Dodaj novi red",
    LOAD: "Učitaj popis",
    SAVE_LIST: "Spremi popis",
    ENABLE_DISABLE_ALL: "Omogući / Neomogući sve",
    DELETE_ALL: "Očisti",
    EXPORT_CSV: "Izvoz u CSV",
    IMPORT_CSV: "Uvezi iz CSV",
    CLEAR_LIST: "Očisti popis?",
    RESET_DATA: "Novi projekt",

    EMAIL: "Email",
    PASSWORD: "Lozinka",
    CONFIRM_PASSWORD: "Potvrdi lozinku",
    SIGN_IN: "Prijavi se",
    SIGN_OUT: "Odjavi se",
    SIGN_UP: "Registriraj se",
    OR: "ili",
    SIGN_IN_GOOGLE: "Prijavi se sa Google računom",
    FORGOT_PASS: "Zaboravljena lozinka?",
    PASS_RESET: "Ponovno postavi lozinku",
    PASS_RESET_MSG: "Unesite email adresu kako bi ste dobili link za postavljanje nove lozinke.",
    PASS_SAVE_MSG: "Unesite novu lozinku.",
    LOGIN_REQUEST: "Prvo se morate prijaviti",

    PDF_PAGE: "stranica",
    REPORT_AN_ISSUE: "Prijavi problem",
    OPTIMIZATION_PRIORITY: "Prioritet optimizacije",
    LEAST_WASTED_AREA: "Najmanje materijala za otpad",
    LEAST_NUMBER_OF_CUTS: "Najmanji broj rezova",

    ZOOM_IN: "Uvećaj",
    ZOOM_OUT: "Umanji",
    INCREASE_FONT_SIZE: "Povećaj Font",
    DECREASE_FONT_SIZE: "Smanji Font",
    RESET_ZOOM: "Vrati na normalan pogled",
    ROTATE_90: "Rotiraj za 90",
    PANEL_LABELS: "Prikaži oznake na pločama",
    COLORED_PANELS: "Ispuni ploče bojama",
    SHOW_CUTS: "Prikaži rezove",
    SHOW_DIMENSIONS: "Dimenzije",

    SAVE_PROJECT: "Spremi projekt",
    LOAD_PROJECT: "Učitaj projekt",
    NO_SAVED_DATA: "Nema spremljenih podataka",
    OVERWRITE: "Prepiši preko",
    SAVE_AS: "Spremi kao",
    ALREADY_EXISTS: "Već postojeće",

    INITIALIZING: "Obrađivanje",
    COMPUTING: "Procjenjivanje",
    SEARCHING_BEST: "Traženje najboljeg rješenja",
    EXPORT_PDF: "Izvezi u PDF",
    EXPORT_IMG: "Izvezi u sliku",
    EXPORTING_PDF: " PDF",
    EXPORTING_IMG: "Stvaranje slike",
    NOTHING_TO_EXPORT: "Ništa za izvoz",
    CLICK_TO_ACCEPT: "Klikni za prihvaćanje rješenja",
    TAP_TO_ACCEPT: "Dotakni za prihvaćanje rješenja",
    MSG_NO_PANELS: "Nema specifikacije ploča",
    MSG_NO_STOCK_PANELS: "Nema specificiranog inventara",
    // TODO: OPTIMIZATION_LEVEL: "Nivo optimizacije",
    IMAGE_PAN_ZOOM: "Zaključavanje i uvećanje",
    FORCE_ONE_STOCK_PANEL: "Iskoristi samo jednu ploču iz zaliha",

    UNITS: "Mjerne jedinice",
    DECIMAL_PLACES: "Decimalna mjesta",
    GENERIC: "Generično (16.5)",
    MM: "Milimetri (16.5 mm)",
    CM: "Centimetri (16.5 cm)",
    INCHES: "Inči (16.5\")",
    FEET_INCHES: "Decimalne stope i inči(1' 4.5\")",
    FEET_INCHES_FRAC: "Frakcione stope i inči(1' 4 1/2\")",
    INCHES_FRAC: "Frakcioni inči(16 1/2\")",

    MATERIAL: "Materijal",
    CREATE_MATERIAL: "Stvori novu vrstu materijala",
    MSG_NO_STOCK_MATERIAL: "Nema dostupnog inventara u traženom materijalu",
    CONSIDER_MATERIALS: "Uzmi materijal u obzir",

    EDGE_BANDING: "Kantiranje rubova",
    EDGE_BAND: "Rub",
    TOP_EDGE_BAND: "Gornji rub",
    LEFT_EDGE_BAND: "Lijevi rub",
    BOTTOM_EDGE_BAND: "Donji rub",
    RIGHT_EDGE_BAND: "Desni rub",
    CREATE_EDGE_BAND: "Stvori novu vrstu ruba",

    ORIENTATION_MATTERS: "Računajte smjer godova",
    NO_GRAIN: "Nema godova",
    HORIZONTAL_GRAIN: "Horizontalni smjer",
    VERTICAL_GRAIN: "Vertikalni smjer",

    CALCULATIONS_PER_WEEK: "Tjedni izračun",
    UNLIMITED: "Neograničeno",
    FREE: "Slobodno",
    MONTHLY: "Mjesečno",
    TERMS_OF_SERVICE: "Uvjeti poslovanja",
    PRIVACY_POLICY: "Privatnost",
    CONTACT_EMAIL: "Kontakt Email:",

    SERVER_UNAVAILABLE: "Server trenutno nije dostupan, molimo pokušajte kasnije.",
    TASK_ALREADY_RUNNING: "Dozvoljeno pokretanje samo jednog izračuna",
    TOO_MANY_PANELS: "Nemoguće izvršiti izračun sa preko 1000 ploča",
    TOO_MANY_STOCK_PANELS: "Nemoguće izvršiti izračun sa preko 1000 ploča",
    LIMITS_REACHED: "Dostignuto je vaše besplatno ograničenje dnevnog izračuna. Razmislite o podršci razvoju.",
    OPEN_RUNNING_CALC: "Otvori pokrenute izračune",

    ABOUT_MSG_1: "CutList Optimizer je aplikacija namijenjena optimizaciji rezanja ploča. Stvara optimizirane uzorke rezanja na temelju dostupnih zaliha umetanjem potrebnih dijelova.",
    ABOUT_MSG_2: "All the features are fully available for free within a limited number of calculations per week.",
    ABOUT_MSG_3: "If you find this app useful, please consider upgrading to the Pro version to support its development. Alternatively, you can upgrade your account within the website and you\'ll have access to both the Android Pro version and website premium features.",
    SUBSCRIPTION_MSG_1: "Contribute to CutList Optimizer by upgrading to a subscription plan.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "Subscription will take effect immediately",
    SUBSCRIPTION_ADDITINAL_MSG_2: "Your PayPal account will be charged automatically at the beginning of each billing cycle",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "First monthly billing cycle begins on the day that you activate service",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "There are no refunds or credits for partial months",
    SUBSCRIPTION_ADDITINAL_MSG_5: "You may cancel your subscription at anytime in your PayPal account and you may continue using the service until your billing period ends",

    TRY_WEB_MSG: "CutList Optimizer dostupan je i na webu. Web inačica pruža optimizirane značajke i koristi namjenski poslužitelj koji omogućuje brže proračune: ",

    SAVED_ITEM_LIMIT_REACHED: "Dosegnuto je maksimalno ograničenje za broj spremljenih stavki."
};
