// Russian
var translationsRU = {
    TITLE: "CutList Optimizer",
    PRO_VERSION: "Версия Про",
    PANEL: "Деталь",
    PANELS: "Детали",
    STOCK_PANEL: "Материал",
    STOCK: "Материал",
    WIDTH: "Ширина",
    HEIGHT: "Длина",
    QUANTITY: "Кол-во",
    LABEL: "Название",
    CUT: "Сечение",
    CUTS: "Сечения",
    TOTAL_CUTS_NBR: "Всего сечений",
    CUT_LENGTH: "Длина сечения",
    TOTAL_CUT_LENGTH: "Длина всех сечений",
    DIM: "Размер",
    USED_AREA: "Использованная площадь",
    TOTAL_USED_AREA: "Общая использованная пл.",
    WASTED_AREA: "Неиспользованная площадь",
    TOTAL_WASTED_AREA: "Общая неиспользованная пл.",
    WASTED_PANELS: "Отходы",
    STATS: "Общие данные",
    SHEET_STATISTICS: "Данные по полотнам",
    NBR_MOSAICS: "Использованный материал",
    UNABLE_TO_FIT: "Не помещается",
    CUT_THICKNESS: "Толщина сечения / лезвия / пропила",

    NAME: "Название",
    NONE: "Неуказанно",
    CALCULATE: "Расчитать",
    ACCEPT: "Принять",
    CANCEL: "Отменить",
    ERROR: "Ошибка",
    OPTIONS: "Опции",
    SETTINGS: "Настройки",
    LANGUAGE: "Язык",
    ENABLE: "Использовать",
    DISABLE: "Не использовать",
    ENABLED: "Используется",
    DISABLED: "Не используется",
    REMOVE: "Удалить",
    REMOVED: "Удалено",
    LOW: "Низкий",
    NORMAL: "Средний",
    HIGH: "Высокий",
    UPGRADE: "Обновить",
    ABOUT: "Oтносительно",
    DELETE: "удалять",
    SAVED: "Сохраненный",
    DELETED: "Исключен",
    LOADED: "Загруженный",
    LOGOUT: "Выйти",
    ADD_NEW: "Добавить новый",

    ADD_LINE: "Добавить строку",
    LOAD: "Загрузить список",
    SAVE_LIST: "Сохранить список",
    ENABLE_DISABLE_ALL: "Включить / отключить все",
    DELETE_ALL: "Удалить всё",
    EXPORT_CSV: "Експорт в CSV",
    IMPORT_CSV: "Импорт из CSV",
    CLEAR_LIST: "Очистить?",
    RESET_DATA: "Очистить данный проeкт",

    EMAIL: "Эл. адрес",
    PASSWORD: "пароль",
    CONFIRM_PASSWORD: "Подтвердите Пароль",
    SIGN_IN: "Войти в систему",
    SIGN_OUT: "Выход",
    SIGN_UP: "Зарегистрироваться",
    OR: "или",
    SIGN_IN_GOOGLE: "Войти через Google",
    FORGOT_PASS: "Забыли свой пароль?",
    PASS_RESET: "Сброс пароля",
    PASS_RESET_MSG: "Пожалуйста, введите адрес электронной почты. Вы получите ссылку для создания нового пароля.",
    PASS_SAVE_MSG: "Пожалуйста, введите ваш новый пароль.",
    LOGIN_REQUEST: "Пожалуйста, войдите сначала",

    PDF_PAGE: "Страница",
    REPORT_AN_ISSUE: "Сообщить о проблеме",
    OPTIMIZATION_PRIORITY: "Предпочтения по оптимизации",
    LEAST_WASTED_AREA: "Меньшая площать отходов",
    LEAST_NUMBER_OF_CUTS: "Меньшее кол-во сечений",

    ZOOM_IN: "Приблизить",
    ZOOM_OUT: "Уменьшить",
    INCREASE_FONT_SIZE: "Увеличить размер шрифта",
    DECREASE_FONT_SIZE: "Уменьшить размер шрифта",
    RESET_ZOOM: "Сбросить вид",
    ROTATE_90: "Повернуть на 90º",
    PANEL_LABELS: "Названия на деталях",
    COLORED_PANELS: "Обозначить неиспользованные детали",
    SHOW_CUTS: "Порядок сечений",
    SHOW_DIMENSIONS: "Габаритные размеры",

    SAVE_PROJECT: "Сохранить проeкт",
    LOAD_PROJECT: "Загрузить проeкт",
    NO_SAVED_DATA: "Нет сохранённых данных!",
    OVERWRITE: "Перезаписать",
    SAVE_AS: "Сохранить как…",
    ALREADY_EXISTS: "Уже существует",

    INITIALIZING: "Инициализация",
    COMPUTING: "Проводится расчёт",
    SEARCHING_BEST: "Проходит поиск лучшего решения",
    EXPORT_PDF: "Експорт в PDF",
    EXPORT_IMG: "Експорт как изображение",
    EXPORTING_PDF: "Создаётся PDF",
    EXPORTING_IMG: "Создаётся изображение",
    NOTHING_TO_EXPORT: "Нечего экспортировать",
    CLICK_TO_ACCEPT: "Шёлкните для принятия решения",
    TAP_TO_ACCEPT: "Дотроньтесь для принятия решения",
    MSG_NO_PANELS: "Вы не уточнили детали",
    MSG_NO_STOCK_PANELS: "Вы не задали материал",
    // TODO: OPTIMIZATION_LEVEL: "Уровень оптимизации",
    IMAGE_PAN_ZOOM: "Разрешить манипуляцию и приближение рисунка",
    FORCE_ONE_STOCK_PANEL: "Использовать только один лист материала",

    UNITS: "Единицы",
    DECIMAL_PLACES: "Десятичные знаки",
    GENERIC: "Без единиц (16.5)",
    MM: "Миллиметры (16.5 mm)",
    CM: "Сантиметры (16.5 cm)",
    INCHES: "Пальцы (16.5\")",
    FEET_INCHES: "Десятичные стопы и пальцы (1' 4.5\")",
    FEET_INCHES_FRAC: "Доли стоп и пальцев (1' 4 1/2\")",
    INCHES_FRAC: "Дробные дюймы (16 1/2\")",

    MATERIAL: "Материал",
    CREATE_MATERIAL: "Создать новый тип материала",
    MSG_NO_STOCK_MATERIAL: "Нет материала данного типа",
    CONSIDER_MATERIALS: "Уточнять материал",

    EDGE_BANDING: "Кромка",
    EDGE_BAND: "Кромка",
    TOP_EDGE_BAND: "Кромка верхней грани",
    LEFT_EDGE_BAND: "Кромка левой грани",
    BOTTOM_EDGE_BAND: "Кромка нижней грани",
    RIGHT_EDGE_BAND: "Кромка правой грани",
    CREATE_EDGE_BAND: "Создать новый тип кромки",

    ORIENTATION_MATTERS: "Уточнять направление текстуры",
    NO_GRAIN: "Не учитывать текстуру",
    HORIZONTAL_GRAIN: "Горизонтальная текстура",
    VERTICAL_GRAIN: "Вертикальная текстура",

    CALCULATIONS_PER_WEEK: "Расчеты за неделю",
    UNLIMITED: "неограниченный",
    FREE: "Cвободно",
    MONTHLY: "ежемесячно",
    TERMS_OF_SERVICE: "Условия обслуживания",
    PRIVACY_POLICY: "Политика конфиденциальности",
    CONTACT_EMAIL: "Почта для связи:",

    SERVER_UNAVAILABLE: "В данный момент сервер не доступен. Попробуйте позже.",
    TASK_ALREADY_RUNNING: "Одновременно можно проводить лишь один расчёт.",
    TOO_MANY_PANELS: "Невозможно выполнить расчет с более чем 1000 панелей",
    TOO_MANY_STOCK_PANELS: "Невозможно выполнить расчет с более чем 1000 листами",
    LIMITS_REACHED: "Ваш бесплатный дневной лимит расчета достигнут. Пожалуйста, подумайте о поддержке развития.",
    OPEN_RUNNING_CALC: "Открытый расчет бега",

    ABOUT_MSG_1: "Программа CutList Optimizer предназначенна для оптимизации нарезки панелей.",
    ABOUT_MSG_2: "Проектирует план нарезки используя доступный материал как можно оптимальнее.",
    ABOUT_MSG_3: "Если вы считаете это приложение полезным, рассмотрите возможность обновления до версии Pro для поддержки его разработки. Кроме того, вы можете обновить свою учетную запись на веб-сайте, и у вас будет доступ как к версии Android Pro, так и к дополнительным функциям веб-сайта.",
    SUBSCRIPTION_MSG_1: "Внесите свой вклад в CutList Optimizer, обновившись до версии Pro.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "Подписка вступит в силу немедленно",
    SUBSCRIPTION_ADDITINAL_MSG_2: "С вашего счета PayPal будет взиматься плата в начале каждого платежного цикла.",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "Первый ежемесячный платежный цикл начинается в день активации услуги",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "Там нет возврата или кредиты за неполные месяцы",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Вы можете отменить свою подписку в любое время в своей учетной записи PayPal, и вы можете продолжать пользоваться этой службой до окончания расчетного периода",

    TRY_WEB_MSG: "CutList Optimizer также доступен в Интернете. Веб-версия предоставляет оптимизированные функции и использует выделенный сервер, обеспечивающий более быстрые вычисления: "
};
