// English
var translationsEN = {

    TITLE: "PECO Optimizer",
    PRO_VERSION: "Pro version",
    PANEL: "Panel",
    PANELS: "Panels",
    STOCK_PANEL: "Stock sheet",
    STOCK: "Stock sheets",
    WIDTH: "Width",
    HEIGHT: "Length",
    QUANTITY: "Qty",
    LABEL: "Label",
    CUT: "Cut",
    CUTS: "Cuts",
    TOTAL_CUTS_NBR: "Total cuts",
    CUT_LENGTH: "Cut length",
    TOTAL_CUT_LENGTH: "Total cut length",
    DIM: "Dim",
    USED_AREA: "Used area",
    TOTAL_USED_AREA: "Total used area",
    WASTED_AREA: "Wasted area",
    TOTAL_WASTED_AREA: "Total wasted area",
    WASTED_PANELS: "Wasted panels",
    STATS: "Global statistics",
    SHEET_STATISTICS: "Sheet statistics",
    NBR_MOSAICS: "Used stock sheets",
    UNABLE_TO_FIT: "Unable to fit",
    CUT_THICKNESS: "Cut / blade / kerf thickness",

    NAME: "Name",
    NONE: "None",
    CALCULATE: "Calculate",
    ACCEPT: "Accept",
    CANCEL: "Cancel",
    ERROR: "Error",
    OPTIONS: "Options",
    SETTINGS: "Settings",
    LANGUAGE: "Language",
    ENABLE: "Enable",
    DISABLE: "Disable",
    ENABLED: "Enabled",
    DISABLED: "Disabled",
    REMOVE: "Remove",
    REMOVED: "Removed",
    LOW: "Low",
    NORMAL: "Normal",
    HIGH: "High",
    UPGRADE: "Upgrade",
    ABOUT: "About",
    DELETE: "Delete",
    SAVED: "Saved",
    DELETED: "Deleted",
    LOADED: "Loaded",
    LOGOUT: "Logout",
    ADD_NEW: "Add new",

    ADD_LINE: "Add new line",
    LOAD: "Load list",
    SAVE_LIST: "Save list",
    ENABLE_DISABLE_ALL: "Enable / Disable all",
    DELETE_ALL: "Clear",
    EXPORT_CSV: "Export to CSV",
    IMPORT_CSV: "Import from CSV",
    CLEAR_LIST: "Clear list?",
    RESET_DATA: "New blank project",

    EMAIL: "Email",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confirm password",
    SIGN_IN: "Sign In",
    SIGN_OUT: "Sign Out",
    SIGN_UP: "Sign Up",
    OR: "or",
    SIGN_IN_GOOGLE: "Sign in with Google",
    FORGOT_PASS: "Forgot your password?",
    PASS_RESET: "Password Reset",
    PASS_RESET_MSG: "Please enter your Email. You'll receive a link to create a new password.",
    PASS_SAVE_MSG: "Please enter your new password.",
    LOGIN_REQUEST: "Please sign in first",

    PDF_PAGE: "page",
    REPORT_AN_ISSUE: "Report an issue",
    OPTIMIZATION_PRIORITY: "Optimization priority",
    LEAST_WASTED_AREA: "Least wasted area",
    LEAST_NUMBER_OF_CUTS: "Least number of cuts",

    ZOOM_IN: "Zoom In",
    ZOOM_OUT: "Zoom Out",
    INCREASE_FONT_SIZE: "Increase Font Size",
    DECREASE_FONT_SIZE: "Decrease Font Size",
    RESET_ZOOM: "Reset View",
    ROTATE_90: "Rotate 90º",
    PANEL_LABELS: "Labels on panels",
    COLORED_PANELS: "Color filled panels",
    SHOW_CUTS: "Cuts order",
    SHOW_DIMENSIONS: "Dimensions",

    SAVE_PROJECT: "Save project",
    LOAD_PROJECT: "Load project",
    NO_SAVED_DATA: "No saved data",
    OVERWRITE: "Overwrite",
    SAVE_AS: "Save as",
    ALREADY_EXISTS: "Already exists",

    INITIALIZING: "Initializing",
    COMPUTING: "Computing",
    SEARCHING_BEST: "Searching for best solution",
    EXPORT_PDF: "Export to PDF",
    EXPORT_IMG: "Export to image",
    EXPORTING_PDF: "Generating PDF",
    EXPORTING_IMG: "Generating image",
    NOTHING_TO_EXPORT: "Nothing to export",

    // TODO: Review other languages
    CLICK_TO_ACCEPT: "Click to accept and stop",
    TAP_TO_ACCEPT: "Tap to accept and stop",

    MSG_NO_PANELS: "No panels specified",
    MSG_NO_STOCK_PANELS: "No stock sheets specified",
    // TODO: OPTIMIZATION_LEVEL: "Optimization level",
    IMAGE_PAN_ZOOM: "Lock Pan & Zoom",
    FORCE_ONE_STOCK_PANEL: "Use only one sheet from stock",

    UNITS: "Units",
    DECIMAL_PLACES: "Decimal places",
    GENERIC: "Generic (16.5)",
    MM: "Millimeters (16.5 mm)",
    CM: "Centimeters (16.5 cm)",
    INCHES: "Inches (16.5\")",
    FEET_INCHES: "Decimal Feet & Inches (1' 4.5\")",
    FEET_INCHES_FRAC: "Fractional Feet & Inches (1' 4 1/2\")",
    INCHES_FRAC: "Fractional Inches (16 1/2\")",

    MATERIAL: "Material",
    CREATE_MATERIAL: "Create new material type",
    MSG_NO_STOCK_MATERIAL: "No available stock sheet of required material",
    CONSIDER_MATERIALS: "Consider material",

    EDGE_BANDING: "Edge banding",
    EDGE_BAND: "Edge band",
    TOP_EDGE_BAND: "Top edge band",
    LEFT_EDGE_BAND: "Left edge band",
    BOTTOM_EDGE_BAND: "Bottom edge band",
    RIGHT_EDGE_BAND: "Right edge band",
    CREATE_EDGE_BAND: "Create new edge band type",

    ORIENTATION_MATTERS: "Consider grain direction",
    NO_GRAIN: "No grain consideration",
    HORIZONTAL_GRAIN: "Grain along width",
    VERTICAL_GRAIN: "Grain along length",

    CALCULATIONS_PER_WEEK: "Calculations per week",
    UNLIMITED: "unlimited",
    FREE: "Free",
    MONTHLY: "month",
    TERMS_OF_SERVICE: "Terms of service",
    PRIVACY_POLICY: "Privacy policy",
    CONTACT_EMAIL: "Contact Email:",

    SERVER_UNAVAILABLE: "Server is currently experiencing some issues, please try again later.",
    TASK_ALREADY_RUNNING: "Only one calculation allowed to run at once",
    TOO_MANY_PANELS: "Unable to perform calculation with more than 5000 panels",
    TOO_MANY_STOCK_PANELS: "Unable to perform calculation with more than 5000 stock sheets",
    LIMITS_REACHED: "Your free daily calculation limit has been reached. Please consider supporting the development.",
    OPEN_RUNNING_CALC: "Open running calculation",

    ABOUT_MSG_1: "CutList Optimizer is an application targeted for panel cutting optimization. It generates optimized cutting patterns based on the available stock sheets by nesting the required parts.",
    ABOUT_MSG_2: "All the features are fully available for free within a limited number of calculations per week.",
    ABOUT_MSG_3: "If you find this app useful, please consider upgrading to the Pro version to support its development. Alternatively, you can upgrade your account within the website and you\'ll have access to both the Android Pro version and website premium features.",
    SUBSCRIPTION_MSG_1: "Contribute to CutList Optimizer by upgrading to a subscription plan.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "Subscription will take effect immediately",
    SUBSCRIPTION_ADDITINAL_MSG_2: "Your PayPal account will be charged automatically at the beginning of each billing cycle",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "First monthly billing cycle begins on the day that you activate service",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "There are no refunds or credits for partial months",
    SUBSCRIPTION_ADDITINAL_MSG_5: "You may cancel your subscription at anytime in your PayPal account and you may continue using the service until your billing period ends",

    SUBSCRIPTION_INVOICE: "VAT Invoice can be requested through ",

    TRY_WEB_MSG: "CutList Optimizer is also available on web. Web version provides optimized features and makes use of a dedicated server providing faster calculations: ",

    SAVED_ITEM_LIMIT_REACHED: "Maximum allowed number of saved items reached",
    SUBSCRIPTION_ACTIVE: "Your subscription is now active. Thank you!",
    SUBSCRIPTION_PLAN: "Subscription plan",
    CONTRIBUTE: "Contribute",
    SUBSCRIBE: "Subscribe",
    ACTIVE: "Active",
    PER_DAY: "per day",
    CLIENT_STATS: "Stats",
    ALLOWED_CALCULATIONS: "Allowed calculations",
    CALCULATION_SPEED: "Calculation speed",
    SAVED_ITEMS: "Saved items",
    PRICE: "Price",
    GOLD: "Gold",
    SILVER: "Silver",

    DIMENSIONS_TO_LABELS: "Fill in labels with dimensions",
    REPLACE_LABELS_QUESTION: "Replace current labels?",

    WHATS_NEW: "What's new",

    FILENAME: "Filename",
    FONT_SIZE: "Font size",
    BIG: "Big",
    HUGE: "Huge",
    SEARCH: "Search",
    RENAME: "Rename",
    RENAMED: "Renamed",
    SAVE: "Save",

    PDF_HEADER_TEXT: "Header text",
    PDF_ADDITIONAL_TEXT: "Additional text",
    PDF_SHOW_SUMMARY: "Show summary",
    PDF_SHOW_DATE: "Show date",
    PDF_SHOW_CUTS_TABLE: "Show cuts table",

    UNSAVED_CHANGES: "Any unsaved changes will be lost. Do you want to continue?",
    ALREADY_EXISTS: "already exists!",

    GENERIC_ERROR_MSG: "An error has occurred!",

    PRO_FEATURE: "Premium Feature",
    PRO_FEATURES: "Premium features",

    CUT_ORIENTATION_PREFERENCE: "Cut Orientation",
    CUT_ORIENTATION_PREFERENCE_NONE: "Optimal",
    CUT_ORIENTATION_PREFERENCE_WIDTH: "Prefer cuts along the width",
    CUT_ORIENTATION_PREFERENCE_LENGTH: "Prefer cuts along the length",

    SUPPORT_PRIORITY: "Priority support",
    MEDIUM: "Medium",

    FORCE_SERVER_SIDE_CALC: "Run calculations on dedicated server",
    ANDROID_PRO_VERSION: "Android Pro app",

    NO_ADS: "No ads",
    SUBSCRIPTION_REQUEST: "This feature requires an account with an active subscription plan",
    UPGRADE_PLAN: "Upgrade",

    SUBSCRIPTION_APLICABLE: "Subscription is applicable to both Website and Android App, unlocking all features for your account",
    SUBSCRIPTION_FEATURES_DEVICE: "Subscription features and saved data will be available to you in any device by simply logging in to your account",

    CANCEL_SUBSCRIPTION: "Are you sure you wish to cancel your active subscription?",
    SUBSCRIPTION_CANCELED: "Subscription canceled",
    SUBSCRIPTION_CANCEL_ERROR: "Something went wrong, please try again later. Alternatively, you may cancel your subscription in your PayPal account or ask via email to support@cutlistoptimizer.com",
    MANAGE_SUBSCRIPTION: "Manage subscription",

    MINIMUM_TRIM_DIMENSION: "Minimum trim dimension",
    GROUP_EQUAL_MOSAICS: "Stack panels with same cut layout",
    AUTO: "Auto",
    NEVER: "Never",
    ALWAYS: "Always",

    SURPLUS: "surplus",
    RESULT: "Result",


    ADDRESS: "Address",
    CITY: "City",
    ZIP_CODE: "Postal / Zip Code",
    COUNTRY: "Country",
    VAT: "Tax / VAT Number",
    BILLING_EMAIL: "Billing Email",

    SHOULD_SEND_INVOICE: "Receive VAT invoice on email",
    BILLING_DETAILS: "Billing details",
    PAYPAL_BILLING_DETAILS_MSG: "PayPal billing details will be used for invoicing",

    PERMIT_PERIOD_ADDITINAL_MSG_1: "One-time payment plan has the same features as the Silver plan",
    PERMIT_PERIOD_ADDITINAL_MSG_2: "Plan features will be available immediately after payment",
    PERMIT_PERIOD_ADDITINAL_MSG_3: "Your saved data will always be available to load even after plan expires",

    PERMIT_PERIOD_ACTIVE: "Your plan is now active. Thank you!",

    WIDTH_1ST: "Dimensions order",

    PANELS_HELPER_TEXT: "Pieces to cut out",
    STOCK_PANELS_HELPER_TEXT: "Sheets to cut from"
};
