// Polish
var translationsPL = {
    TITLE: "CutList Optimizer",
    PRO_VERSION: "Wersja Pro",
    PANEL: "Panel",
    PANELS: "Panele",
    STOCK_PANEL: "Arkusz",
    STOCK: "Arkusze surowca",
    WIDTH: "Szerokość",
    HEIGHT: "Długość",
    QUANTITY: "Ilość",
    LABEL: "Opis",
    CUT: "Cięcie",
    CUTS: "Cięcia",
    TOTAL_CUTS_NBR: "Ilość cięć",
    CUT_LENGTH: "Długość cięcia",
    TOTAL_CUT_LENGTH: "Całkowita długość cięcia",
    DIM: "Wym",
    USED_AREA: "Zużyta powierzchnia",
    TOTAL_USED_AREA: "Całkowita zużyta powierzchnia",
    WASTED_AREA: "Powierzchnia odpadu",
    TOTAL_WASTED_AREA: "Całkowita powierzchnia odpadu",
    WASTED_PANELS: "Panele odpadowe",
    STATS: "Statystyka globalna",
    SHEET_STATISTICS: "Statystyka arkusza",
    NBR_MOSAICS: "Użyte arkusze surowca",
    UNABLE_TO_FIT: "Niemożliwe do wpasowania",
    CUT_THICKNESS: "Szer. cięcia / ostrze / szrank",

    NAME: "Nazwa",
    NONE: "Brak",
    CALCULATE: "Oblicz",
    ACCEPT: "Akceptuj",
    CANCEL: "Anuluj",
    ERROR: "Błąd",
    OPTIONS: "Opcje",
    SETTINGS: "Ustawienia",
    LANGUAGE: "Język",
    ENABLE: "Włącz",
    DISABLE: "Wyłącz",
    ENABLED: "Włączone",
    DISABLED: "Wyłączone",
    REMOVE: "Usuń",
    REMOVED: "Usunięty",
    LOW: "Niski",
    NORMAL: "Normalny",
    HIGH: "Wysoki",
    UPGRADE: "Zmodernizować",
    ABOUT: "O aplikacji",
    DELETE: "Usunąć",
    SAVED: "Zapisano",
    DELETED: "Usunięte",
    LOADED: "Załadowany",
    LOGOUT: "Wyloguj",
    ADD_NEW: "Dodaj nowy",

    ADD_LINE: "Dodaj nową linię",
    LOAD: "Wczytaj listę",
    SAVE_LIST: "Zapisz listę",
    ENABLE_DISABLE_ALL: "Włącz / wyłącz wszystkie",
    DELETE_ALL: "Wyczyść",
    EXPORT_CSV: "Eksportuj do CSV",
    IMPORT_CSV: "Importuj z CSV",
    CLEAR_LIST: "Wyczyścić listę?",
    RESET_DATA: "Wyczyść wszystkie dane",

    EMAIL: "E-mail",
    PASSWORD: "Hasło",
    CONFIRM_PASSWORD: "Potwierdź hasło",
    SIGN_IN: "Zaloguj się",
    SIGN_OUT: "Wyloguj się",
    SIGN_UP: "Zapisz się",
    OR: "lub",
    SIGN_IN_GOOGLE: "Zaloguj się za pomocą Google",
    FORGOT_PASS: "Zapomniałeś hasła?",
    PASS_RESET: "Zresetowanie hasła",
    PASS_RESET_MSG: "Proszę podać swój adres e-mail. Otrzymasz link do utworzenia nowego hasła.",
    PASS_SAVE_MSG: "Proszę podać nowe hasło.",
    LOGIN_REQUEST: "Proszę się najpierw zalogować",

    PDF_PAGE: "strona",
    REPORT_AN_ISSUE: "Zgłoś problem",
    OPTIMIZATION_PRIORITY: "Priorytet optymalizacji",
    LEAST_WASTED_AREA: "Najmniejszy odpad",
    LEAST_NUMBER_OF_CUTS: "Najmniejsza liczba cięć",

    ZOOM_IN: "Powiększ -or- Przybliż",
    ZOOM_OUT: "Pomniejsz -or- Oddal",
    INCREASE_FONT_SIZE: "Zwiększ rozmiar czcionki",
    DECREASE_FONT_SIZE: "Zmniejsz rozmiar czcionki",
    RESET_ZOOM: "Zresetuj widok",
    ROTATE_90: "Obróć o 90º",
    PANEL_LABELS: "Opisy na panelach",
    COLORED_PANELS: "Kolorowe panele",
    SHOW_CUTS: "Kolejność cięcia",
    SHOW_DIMENSIONS: "Wymiary",

    SAVE_PROJECT: "Zapisz projekt",
    LOAD_PROJECT: "Wczytaj projekt",
    NO_SAVED_DATA: "Brak zapisanych danych!",
    OVERWRITE: "Nadpisz",
    SAVE_AS: "Zapisz jako",
    ALREADY_EXISTS: "Już istnieje",

    INITIALIZING: "Rozpoczęcie",
    COMPUTING: "Przetwarzanie",
    SEARCHING_BEST: "Poszukiwanie najlepszych rozwiązań",
    EXPORT_PDF: "Eksportuj do PDF",
    EXPORT_IMG: "Eksportuj jako obraz",
    EXPORTING_PDF: "Generowanie PDF",
    EXPORTING_IMG: "Generowanie obrazu",
    NOTHING_TO_EXPORT: "Nic do wyeksportowania",
    CLICK_TO_ACCEPT: "Kliknij, by zaakceptować rozwiązanie",
    TAP_TO_ACCEPT: "Stuknij, by zaakceptować rozwiązanie",
    MSG_NO_PANELS: "Nie określono paneli",
    MSG_NO_STOCK_PANELS: "Nie określono arkuszy surowca",
    // TODO: OPTIMIZATION_LEVEL: "Poziom optymalizacji",
    IMAGE_PAN_ZOOM: "Włącz przesuwanie i przybliżanie obrazu",
    FORCE_ONE_STOCK_PANEL: "Użyj tylko jednego typu arkusza surowca",

    UNITS: "Jednostki",
    DECIMAL_PLACES: "Miejsca dziesiętne",
    GENERIC: "Ogólne (16.5)",
    MM: "Milimetry (16.5 mm)",
    CM: "Centymetry (16.5 cm)",
    INCHES: "Cale (16.5\")",
    FEET_INCHES: "Stopy dziesiętne i Cale (1' 4.5\")",
    FEET_INCHES_FRAC: "Stopy ułamkowe i Cale (1' 4 1/2\")",
    INCHES_FRAC: "Cale ułamkowe (16 1/2\")",

    MATERIAL: "Materiał",
    CREATE_MATERIAL: "Utwórz nowy typ materiału",
    MSG_NO_STOCK_MATERIAL: "Brak dostępnych arkuszy surowca wymaganego materiału",
    CONSIDER_MATERIALS: "Uwzględnij materiał",

    EDGE_BANDING: "Oklejanie krawędzi",
    EDGE_BAND: "Okleina krawędzi",
    TOP_EDGE_BAND: "Górna okleina krawędzi",
    LEFT_EDGE_BAND: "Lewa okleina krawędzi",
    BOTTOM_EDGE_BAND: "Dolna okleina krawędzi",
    RIGHT_EDGE_BAND: "Prawa okleina krawędzi",
    CREATE_EDGE_BAND: "Utwórz nowy typ okleiny krawędzi",

    ORIENTATION_MATTERS: "Uwzględnij układ włókien",
    NO_GRAIN: "Bez uwzględnienia włókien",
    HORIZONTAL_GRAIN: "Słoje poziome",
    VERTICAL_GRAIN: "Słoje pionowe",

    CALCULATIONS_PER_WEEK: "Obliczenia na tydzień",
    UNLIMITED: "bez limitu",
    FREE: "Darmowy",
    MONTHLY: "miesięczny",
    TERMS_OF_SERVICE: "Warunki usługi",
    PRIVACY_POLICY: "Polityka prywatności",
    CONTACT_EMAIL: "Kontaktowy adres e-mail:",

    SERVER_UNAVAILABLE: "Serwer doświadcza obecnie pewnych problemów, spróbuj ponownie później.",
    TASK_ALREADY_RUNNING: "Jednocześnie można uruchomić tylko jedno obliczenie",
    TOO_MANY_PANELS: "Nie można wykonać obliczeń dla więcej niż 1000 paneli",
    TOO_MANY_STOCK_PANELS: "Nie można wykonać obliczeń dla ponad 1000 arkuszy magazynowych",
    LIMITS_REACHED: "Twój dzienny limit obliczeniowy został osiągnięty. Proszę rozważyć wsparcie rozwoju.",
    OPEN_RUNNING_CALC: "Otwarte obliczenia bieżące",

    ABOUT_MSG_1: "CutList Optimizer jest aplikacją przeznaczoną do optymalizacji cięcia paneli.",
    ABOUT_MSG_2: "Generuje zoptymalizowane wzory cięcia w oparciu o dostępne arkusze surowca poprzez zagnieżdżanie wymaganych części.",
    ABOUT_MSG_3: "Jeśli uznasz tę aplikację za przydatną, rozważ aktualizację do wersji Pro, aby wesprzeć jej rozwój. Alternatywnie możesz uaktualnić swoje konto w witrynie, a będziesz mieć dostęp zarówno do wersji Android Pro, jak i funkcji premium witryny.",
    SUBSCRIPTION_MSG_1: "Wnieś wkład do Optymalizatora CutList poprzez aktualizację do wersji Pro.",
    SUBSCRIPTION_ADDITINAL_MSG_1: "Subskrypcja wejdzie w życie natychmiast",
    SUBSCRIPTION_ADDITINAL_MSG_2: "Twoje konto PayPal zostanie automatycznie obciążone na początku każdego cyklu rozliczeniowego",
    //SUBSCRIPTION_ADDITINAL_MSG_3: "Pierwszy miesięczny cykl rozliczeniowy rozpoczyna się w dniu aktywacji usługi",
    //SUBSCRIPTION_ADDITINAL_MSG_4: "Brak refundacji lub kredytów za częściowe miesiące",
    SUBSCRIPTION_ADDITINAL_MSG_5: "Możesz anulować subskrypcję w dowolnym momencie na swoim koncie PayPal i możesz nadal korzystać z usługi, aż do końca okresu rozliczeniowego",

    TRY_WEB_MSG: "CutList Optimizer jest również dostępny w Internecie. Wersja internetowa zapewnia zoptymalizowane funkcje i wykorzystuje dedykowany serwer zapewniający szybsze obliczenia: "
};
